export interface DocumentVersion {
  version: number;
  date: string;
  uploadedBy: string;
  uploadedByRole: string;
  size: string;
  notes: string;
}

export interface DocumentItem {
  id: string;
  name: string;
  type: string;
  folder: string;
  propertyId: string;
  propertyName: string;
  landlordId?: string;
  landlordName?: string;
  tenantId?: string;
  tenantName?: string;
  tenancyId?: string;
  tenancyRef?: string;
  complianceRecordId?: string;
  complianceType?: string;
  date: string;
  size: string;
  description: string;
  fileType: string;
  icon: string;
  color: string;
  uploadedBy: string;
  uploadedByRole: string;
  versions: DocumentVersion[];
  access: string[];
}

export interface LinkableEntity {
  id: string;
  name: string;
  type: "property" | "landlord" | "tenant" | "tenancy" | "compliance";
  subtitle?: string;
}

export const documentFolders = [
  { id: "all", name: "All Documents", icon: "ri-folder-line" },
  { id: "Tenancy Agreements", name: "Tenancy Agreements", icon: "ri-file-text-line" },
  { id: "Inventories", name: "Inventories", icon: "ri-file-list-line" },
  { id: "Compliance Certificates", name: "Compliance Certificates", icon: "ri-file-shield-line" },
  { id: "Inspection Reports", name: "Inspection Reports", icon: "ri-clipboard-line" },
  { id: "Financial", name: "Financial", icon: "ri-file-chart-line" },
  { id: "Property Photos", name: "Property Photos", icon: "ri-image-line" },
  { id: "Contractor Documents", name: "Contractor Documents", icon: "ri-briefcase-line" },
  { id: "Guides", name: "Guides", icon: "ri-book-open-line" },
];

export const documentTypes = [
  "All",
  "Tenancy Agreement",
  "Inventory",
  "Gas Safety",
  "EICR",
  "EPC",
  "Legionella",
  "Smoke Alarm",
  "Insurance",
  "Inspection Report",
  "Invoice",
  "Receipt",
  "Deposit Certificate",
  "Right to Rent",
  "Maintenance Quote",
  "Property Photo",
  "Contractor Insurance",
  "Contractor Certification",
  "Completion Photo",
  "Guide",
  "Quote",
  "Other",
];

export const linkableLandlords: LinkableEntity[] = [
  { id: "l1", name: "James Thompson", type: "landlord", subtitle: "3 properties" },
  { id: "l2", name: "Susan Wright", type: "landlord", subtitle: "5 properties" },
  { id: "l3", name: "Michael Brown", type: "landlord", subtitle: "2 properties" },
  { id: "l4", name: "David Chen", type: "landlord", subtitle: "1 property" },
  { id: "l5", name: "Emma Wilson", type: "landlord", subtitle: "4 properties" },
  { id: "l6", name: "Robert Clark", type: "landlord", subtitle: "2 properties" },
];

export const linkableTenants: LinkableEntity[] = [
  { id: "t1", name: "Sarah Jenkins", type: "tenant", subtitle: "Rose Court Flat 2A" },
  { id: "t2", name: "John Miller", type: "tenant", subtitle: "Riverside Court" },
  { id: "t3", name: "Emma White", type: "tenant", subtitle: "Oak Lane" },
  { id: "t4", name: "Tom Harris", type: "tenant", subtitle: "High Street, Leeds" },
  { id: "t5", name: "Lisa Green", type: "tenant", subtitle: "The Crescent, Birmingham" },
  { id: "t6", name: "Mark Davies", type: "tenant", subtitle: "Rose Avenue, Manchester" },
];

export const linkableTenancies: LinkableEntity[] = [
  { id: "tn1", name: "TNCY-2024-001", type: "tenancy", subtitle: "Rose Court Flat 2A — Sarah Jenkins" },
  { id: "tn2", name: "TNCY-2024-002", type: "tenancy", subtitle: "Riverside Court — John Miller" },
  { id: "tn3", name: "TNCY-2025-003", type: "tenancy", subtitle: "Oak Lane — Emma White" },
  { id: "tn4", name: "TNCY-2025-004", type: "tenancy", subtitle: "High Street — Tom Harris" },
  { id: "tn5", name: "TNCY-2024-005", type: "tenancy", subtitle: "The Crescent — Lisa Green" },
];

export const linkableCompliance: LinkableEntity[] = [
  { id: "c1", name: "Gas Safety — Rose Court", type: "compliance", subtitle: "Expires 12 Mar 2027" },
  { id: "c2", name: "EICR — Rose Court", type: "compliance", subtitle: "Expires 19 Jun 2026" },
  { id: "c3", name: "EPC — Rose Court", type: "compliance", subtitle: "Expires 16 Aug 2028" },
  { id: "c4", name: "Gas Safety — Riverside", type: "compliance", subtitle: "Expires 20 Nov 2026" },
  { id: "c5", name: "EPC — Maple Gardens", type: "compliance", subtitle: "Expired 03 Jan 2026" },
  { id: "c6", name: "Legionella — Riverside", type: "compliance", subtitle: "Expires 15 Jun 2026" },
];

export const allDocuments: DocumentItem[] = [
  {
    id: "doc1",
    name: "Tenancy Agreement - John Miller.pdf",
    type: "Tenancy Agreement",
    folder: "Tenancy Agreements",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    landlordId: "l2",
    landlordName: "Susan Wright",
    tenantId: "t2",
    tenantName: "John Miller",
    tenancyId: "tn2",
    tenancyRef: "TNCY-2024-002",
    date: "15 Sep 2024",
    size: "1.2 MB",
    description: "Signed Assured Shorthold Tenancy agreement for 24-month fixed term",
    fileType: "pdf",
    icon: "ri-file-text-line",
    color: "bg-[#3B82F6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "15 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "1.2 MB", notes: "Initial signed agreement" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc2",
    name: "Tenancy Agreement - Emma Wilson.pdf",
    type: "Tenancy Agreement",
    folder: "Tenancy Agreements",
    propertyId: "p2",
    propertyName: "Riverside Court",
    landlordId: "l5",
    landlordName: "Emma Wilson",
    tenantId: "t4",
    tenantName: "Tom Harris",
    tenancyId: "tn4",
    tenancyRef: "TNCY-2025-004",
    date: "05 Aug 2024",
    size: "1.1 MB",
    description: "Signed AST for 24-month fixed term at Riverside Court",
    fileType: "pdf",
    icon: "ri-file-text-line",
    color: "bg-[#3B82F6]",
    uploadedBy: "James Hart",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "05 Aug 2024", uploadedBy: "James Hart", uploadedByRole: "Agent", size: "1.1 MB", notes: "Initial signed agreement" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc3",
    name: "Tenancy Agreement - Michael Brown.pdf",
    type: "Tenancy Agreement",
    folder: "Tenancy Agreements",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    landlordId: "l3",
    landlordName: "Michael Brown",
    tenantId: "t3",
    tenantName: "Emma White",
    tenancyId: "tn3",
    tenancyRef: "TNCY-2025-003",
    date: "12 Mar 2024",
    size: "1.3 MB",
    description: "Signed AST for 24-month fixed term at Maple Gardens House",
    fileType: "pdf",
    icon: "ri-file-text-line",
    color: "bg-[#3B82F6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "12 Mar 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "1.3 MB", notes: "Initial signed agreement" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc4",
    name: "Inventory Check-in - Rose Court Flat 2A.pdf",
    type: "Inventory",
    folder: "Inventories",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "15 Sep 2024",
    size: "2.4 MB",
    description: "Full inventory and condition report at move-in with photos",
    fileType: "pdf",
    icon: "ri-file-list-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "15 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "2.4 MB", notes: "Initial check-in inventory" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc5",
    name: "Inventory Check-in - Riverside Court.pdf",
    type: "Inventory",
    folder: "Inventories",
    propertyId: "p2",
    propertyName: "Riverside Court",
    date: "05 Aug 2024",
    size: "3.1 MB",
    description: "Full inventory and condition report at move-in",
    fileType: "pdf",
    icon: "ri-file-list-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "James Hart",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "05 Aug 2024", uploadedBy: "James Hart", uploadedByRole: "Agent", size: "3.1 MB", notes: "Initial check-in inventory" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc6",
    name: "Inventory Check-in - Maple Gardens House.pdf",
    type: "Inventory",
    folder: "Inventories",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    date: "12 Mar 2024",
    size: "4.8 MB",
    description: "Full inventory and condition report at move-in with 50+ photos",
    fileType: "pdf",
    icon: "ri-file-list-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "12 Mar 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "4.8 MB", notes: "Initial check-in inventory" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc7",
    name: "Gas Safety Certificate - Rose Court 2026.pdf",
    type: "Gas Safety",
    folder: "Compliance Certificates",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    complianceRecordId: "c1",
    complianceType: "Gas Safety",
    date: "13 Mar 2026",
    size: "0.8 MB",
    description: "Annual gas safety certificate CP12 valid until 12 Mar 2027",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "SafeGas Engineers",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "13 Mar 2026", uploadedBy: "SafeGas Engineers", uploadedByRole: "Contractor", size: "0.8 MB", notes: "Annual gas safety check" },
      { version: 2, date: "13 Mar 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "0.8 MB", notes: "Verified and re-uploaded" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc8",
    name: "EICR Report - Rose Court 2021.pdf",
    type: "EICR",
    folder: "Compliance Certificates",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    complianceRecordId: "c2",
    complianceType: "EICR",
    date: "19 Jun 2021",
    size: "1.4 MB",
    description: "Electrical Installation Condition Report with C2 observation",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "London Electrical Services",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "19 Jun 2021", uploadedBy: "London Electrical Services", uploadedByRole: "Contractor", size: "1.4 MB", notes: "5-year EICR report" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc9",
    name: "EPC Certificate - Rose Court.pdf",
    type: "EPC",
    folder: "Compliance Certificates",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    complianceRecordId: "c3",
    complianceType: "EPC",
    date: "16 Aug 2018",
    size: "0.5 MB",
    description: "Energy Performance Certificate rating C valid until 2028",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "EPC Direct London",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "16 Aug 2018", uploadedBy: "EPC Direct London", uploadedByRole: "Contractor", size: "0.5 MB", notes: "10-year EPC certificate" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc10",
    name: "EPC Certificate - Maple Gardens.pdf",
    type: "EPC",
    folder: "Compliance Certificates",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    complianceRecordId: "c5",
    complianceType: "EPC",
    date: "03 Jan 2016",
    size: "0.6 MB",
    description: "Energy Performance Certificate rating D expired Jan 2026",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "EPC Direct Wales",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "03 Jan 2016", uploadedBy: "EPC Direct Wales", uploadedByRole: "Contractor", size: "0.6 MB", notes: "Original EPC" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc11",
    name: "Gas Safety Certificate - Riverside 2025.pdf",
    type: "Gas Safety",
    folder: "Compliance Certificates",
    propertyId: "p2",
    propertyName: "Riverside Court",
    complianceRecordId: "c4",
    complianceType: "Gas Safety",
    date: "21 Nov 2025",
    size: "0.7 MB",
    description: "Annual gas safety certificate valid until 20 Nov 2026",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "Bristol Gas Solutions",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "21 Nov 2025", uploadedBy: "Bristol Gas Solutions", uploadedByRole: "Contractor", size: "0.7 MB", notes: "Annual gas safety check" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc12",
    name: "Routine Inspection Report - Rose Court Feb 2026.pdf",
    type: "Inspection Report",
    folder: "Inspection Reports",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "10 Feb 2026",
    size: "1.8 MB",
    description: "Quarterly routine inspection with 20 photos and notes",
    fileType: "pdf",
    icon: "ri-clipboard-line",
    color: "bg-[#14B8A6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "10 Feb 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "1.8 MB", notes: "Routine inspection completed" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc13",
    name: "Move-in Inspection - Riverside Court.pdf",
    type: "Inspection Report",
    folder: "Inspection Reports",
    propertyId: "p2",
    propertyName: "Riverside Court",
    date: "05 Aug 2024",
    size: "3.2 MB",
    description: "Full move-in inspection with detailed condition photos",
    fileType: "pdf",
    icon: "ri-clipboard-line",
    color: "bg-[#14B8A6]",
    uploadedBy: "James Hart",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "05 Aug 2024", uploadedBy: "James Hart", uploadedByRole: "Agent", size: "3.2 MB", notes: "Move-in inspection completed" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc14",
    name: "Routine Inspection - Maple Gardens Mar 2026.pdf",
    type: "Inspection Report",
    folder: "Inspection Reports",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    date: "18 Mar 2026",
    size: "2.6 MB",
    description: "Quarterly routine inspection with garden fence damage noted",
    fileType: "pdf",
    icon: "ri-clipboard-line",
    color: "bg-[#14B8A6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "18 Mar 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "2.6 MB", notes: "Routine inspection completed" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc15",
    name: "Boiler Service Invoice - Mar 2026.pdf",
    type: "Invoice",
    folder: "Financial",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "12 Mar 2026",
    size: "0.5 MB",
    description: "Boiler service invoice from SafeGas Engineers Ltd",
    fileType: "pdf",
    icon: "ri-file-chart-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "SafeGas Engineers",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "12 Mar 2026", uploadedBy: "SafeGas Engineers", uploadedByRole: "Contractor", size: "0.5 MB", notes: "Boiler service invoice" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc16",
    name: "Rent Receipt - March 2026.pdf",
    type: "Receipt",
    folder: "Financial",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "01 Mar 2026",
    size: "0.2 MB",
    description: "Rent receipt for March 2026 - £1,850",
    fileType: "pdf",
    icon: "ri-file-chart-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "01 Mar 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "0.2 MB", notes: "Rent receipt issued" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc17",
    name: "Building Insurance Policy 2026.pdf",
    type: "Insurance",
    folder: "Financial",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    date: "01 Mar 2026",
    size: "3.2 MB",
    description: "Landlord building insurance policy with Aviva",
    fileType: "pdf",
    icon: "ri-shield-line",
    color: "bg-[#EF4444]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "01 Mar 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "3.2 MB", notes: "Insurance policy renewed" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc18",
    name: "Deposit Protection Certificate.pdf",
    type: "Deposit Certificate",
    folder: "Financial",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "15 Sep 2024",
    size: "0.3 MB",
    description: "MyDeposits scheme registration certificate for £1,850",
    fileType: "pdf",
    icon: "ri-file-chart-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "15 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "0.3 MB", notes: "Deposit registered" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc19",
    name: "Property Photo - Rose Court Living Room.jpg",
    type: "Property Photo",
    folder: "Property Photos",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "10 Feb 2026",
    size: "2.1 MB",
    description: "Living room photo from Feb 2026 inspection",
    fileType: "jpg",
    icon: "ri-image-line",
    color: "bg-[#EC4899]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "10 Feb 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "2.1 MB", notes: "Inspection photo" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc20",
    name: "Property Photo - Maple Gardens Garden.jpg",
    type: "Property Photo",
    folder: "Property Photos",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    date: "18 Mar 2026",
    size: "3.4 MB",
    description: "Garden photo showing fence damage after storm",
    fileType: "jpg",
    icon: "ri-image-line",
    color: "bg-[#EC4899]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "18 Mar 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "3.4 MB", notes: "Fence damage photo" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc21",
    name: "GreenPlumb Ltd - Public Liability Insurance.pdf",
    type: "Contractor Insurance",
    folder: "Contractor Documents",
    propertyId: "all",
    propertyName: "All Properties",
    date: "01 Jan 2026",
    size: "1.1 MB",
    description: "GreenPlumb Ltd public liability insurance £2M cover",
    fileType: "pdf",
    icon: "ri-briefcase-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "GreenPlumb Ltd",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "01 Jan 2026", uploadedBy: "GreenPlumb Ltd", uploadedByRole: "Contractor", size: "1.1 MB", notes: "Insurance certificate submitted" },
      { version: 2, date: "02 Jan 2026", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "1.1 MB", notes: "Verified and approved" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc22",
    name: "GreenPlumb Ltd - Gas Safe Registration.pdf",
    type: "Contractor Certification",
    folder: "Contractor Documents",
    propertyId: "all",
    propertyName: "All Properties",
    date: "01 Jan 2026",
    size: "0.4 MB",
    description: "Gas Safe Register certificate for GreenPlumb Ltd",
    fileType: "pdf",
    icon: "ri-briefcase-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "GreenPlumb Ltd",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "01 Jan 2026", uploadedBy: "GreenPlumb Ltd", uploadedByRole: "Contractor", size: "0.4 MB", notes: "Gas Safe cert submitted" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc23",
    name: "SecureFix - Public Liability Insurance.pdf",
    type: "Contractor Insurance",
    folder: "Contractor Documents",
    propertyId: "all",
    propertyName: "All Properties",
    date: "15 Mar 2026",
    size: "0.9 MB",
    description: "SecureFix locksmiths PLI £1M cover",
    fileType: "pdf",
    icon: "ri-briefcase-line",
    color: "bg-[#F59E0B]",
    uploadedBy: "SecureFix",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "15 Mar 2026", uploadedBy: "SecureFix", uploadedByRole: "Contractor", size: "0.9 MB", notes: "Insurance certificate submitted" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc24",
    name: "How to Rent Guide.pdf",
    type: "Guide",
    folder: "Guides",
    propertyId: "all",
    propertyName: "All Properties",
    date: "15 Sep 2024",
    size: "1.5 MB",
    description: "Government how to rent guide for tenants",
    fileType: "pdf",
    icon: "ri-book-open-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "15 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "1.5 MB", notes: "Government guide provided" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc25",
    name: "Rent Payment Schedule.pdf",
    type: "Guide",
    folder: "Guides",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "15 Sep 2024",
    size: "0.4 MB",
    description: "Monthly rent payment schedule and standing order details",
    fileType: "pdf",
    icon: "ri-book-open-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "15 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "0.4 MB", notes: "Payment schedule provided" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc26",
    name: "Boiler Repair Quote - Rose Court.pdf",
    type: "Maintenance Quote",
    folder: "Financial",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "28 May 2026",
    size: "0.6 MB",
    description: "Boiler pressure valve replacement quote from GreenPlumb Ltd",
    fileType: "pdf",
    icon: "ri-file-chart-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "GreenPlumb Ltd",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "28 May 2026", uploadedBy: "GreenPlumb Ltd", uploadedByRole: "Contractor", size: "0.6 MB", notes: "Quote submitted" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc27",
    name: "Fence Repair Invoice - Maple Gardens.pdf",
    type: "Invoice",
    folder: "Financial",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    date: "28 Mar 2026",
    size: "0.7 MB",
    description: "Fence panel replacement invoice from BuildRight Construction",
    fileType: "pdf",
    icon: "ri-file-chart-line",
    color: "bg-[#8B5CF6]",
    uploadedBy: "BuildRight Construction",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "28 Mar 2026", uploadedBy: "BuildRight Construction", uploadedByRole: "Contractor", size: "0.7 MB", notes: "Invoice submitted" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc28",
    name: "Smoke Alarm Test Certificate - Rose Court.pdf",
    type: "Smoke Alarm",
    folder: "Compliance Certificates",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "01 Jul 2025",
    size: "0.4 MB",
    description: "Annual smoke alarm test certificate valid until 01 Jul 2026",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "FireSafe London",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "01 Jul 2025", uploadedBy: "FireSafe London", uploadedByRole: "Contractor", size: "0.4 MB", notes: "Annual smoke alarm test" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc29",
    name: "Legionella Assessment - Riverside.pdf",
    type: "Legionella",
    folder: "Compliance Certificates",
    propertyId: "p2",
    propertyName: "Riverside Court",
    complianceRecordId: "c6",
    complianceType: "Legionella",
    date: "16 Jun 2025",
    size: "0.5 MB",
    description: "Annual legionella risk assessment valid until 15 Jun 2026",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "WaterSafe Compliance",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "16 Jun 2025", uploadedBy: "WaterSafe Compliance", uploadedByRole: "Contractor", size: "0.5 MB", notes: "Annual legionella assessment" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc30",
    name: "Completion Photo - Boiler Repair.jpg",
    type: "Completion Photo",
    folder: "Contractor Documents",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    date: "22 May 2026",
    size: "1.8 MB",
    description: "Photo of completed boiler repair work",
    fileType: "jpg",
    icon: "ri-image-line",
    color: "bg-[#EC4899]",
    uploadedBy: "GreenPlumb Ltd",
    uploadedByRole: "Contractor",
    versions: [
      { version: 1, date: "22 May 2026", uploadedBy: "GreenPlumb Ltd", uploadedByRole: "Contractor", size: "1.8 MB", notes: "Completion photo uploaded" },
    ],
    access: ["agent", "landlord", "tenant"],
  },
  {
    id: "doc31",
    name: "Right to Rent Check - Sarah Jenkins.pdf",
    type: "Right to Rent",
    folder: "Compliance Certificates",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    tenantId: "t1",
    tenantName: "Sarah Jenkins",
    date: "10 Sep 2024",
    size: "0.6 MB",
    description: "Right to Rent verification — British passport and immigration status confirmed",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "Sarah Collins",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "10 Sep 2024", uploadedBy: "Sarah Collins", uploadedByRole: "Agent", size: "0.6 MB", notes: "Right to Rent check completed" },
    ],
    access: ["agent", "landlord"],
  },
  {
    id: "doc32",
    name: "Right to Rent Check - John Miller.pdf",
    type: "Right to Rent",
    folder: "Compliance Certificates",
    propertyId: "p2",
    propertyName: "Riverside Court",
    tenantId: "t2",
    tenantName: "John Miller",
    date: "01 Aug 2024",
    size: "0.5 MB",
    description: "Right to Rent verification — UK birth certificate and proof of address",
    fileType: "pdf",
    icon: "ri-file-shield-line",
    color: "bg-[#10B981]",
    uploadedBy: "James Hart",
    uploadedByRole: "Agent",
    versions: [
      { version: 1, date: "01 Aug 2024", uploadedBy: "James Hart", uploadedByRole: "Agent", size: "0.5 MB", notes: "Right to Rent check completed" },
    ],
    access: ["agent", "landlord"],
  },
];

export const getDocumentsByRole = (role: string, propertyId?: string): DocumentItem[] => {
  return allDocuments.filter((doc) => {
    const hasRoleAccess = doc.access.includes(role);
    if (!hasRoleAccess) return false;
    if (propertyId && doc.propertyId !== "all" && doc.propertyId !== propertyId) return false;
    return true;
  });
};

export const propertiesForDocs = [
  { id: "all", name: "All Properties" },
  { id: "p1", name: "Rose Court Flat 2A" },
  { id: "p2", name: "Riverside Court" },
  { id: "p3", name: "Maple Gardens House" },
];