export const arrearsData: Array<{
  id: number;
  property: string;
  tenant: string;
  landlord: string;
  rentAmount: number;
  dueDate: string;
  paidDate: string | null;
  outstanding: number;
  arrearsMonths: number;
  totalArrears: number;
  riskRating: "Low" | "Medium" | "High";
  lastContact: string;
  contactMethod: string;
  tenantPhone: string;
  tenantEmail: string;
  previousLate: number;
  paymentHistory: { month: string; amount: number; date: string | null; status: string; daysLate: number }[];
  communications: { date: string; type: string; subject: string; status: string; agent: string }[];
}> = [
  {
    id: 1,
    property: "12 Rose Avenue",
    tenant: "John Miller",
    landlord: "James Richardson",
    rentAmount: 1850,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 1850,
    arrearsMonths: 1,
    totalArrears: 1850,
    riskRating: "Low",
    lastContact: "5 Jun 2026",
    contactMethod: "Email Reminder",
    tenantPhone: "+44 7700 900123",
    tenantEmail: "john.miller@email.com",
    previousLate: 0,
    paymentHistory: [
      { month: "May 2026", amount: 1850, date: "1 May 2026", status: "Paid", daysLate: 0 },
      { month: "Apr 2026", amount: 1850, date: "1 Apr 2026", status: "Paid", daysLate: 0 },
      { month: "Mar 2026", amount: 1850, date: "1 Mar 2026", status: "Paid", daysLate: 0 },
    ],
    communications: [
      { date: "5 Jun 2026", type: "Email", subject: "Rent Reminder — June 2026", status: "Sent", agent: "Sarah Cooper" },
    ],
  },
  {
    id: 2,
    property: "8 The Crescent",
    tenant: "Michael Brown",
    landlord: "Margaret Hughes",
    rentAmount: 1650,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 1650,
    arrearsMonths: 1,
    totalArrears: 1650,
    riskRating: "Medium",
    lastContact: "4 Jun 2026",
    contactMethod: "SMS Reminder",
    tenantPhone: "+44 7700 900456",
    tenantEmail: "michael.brown@email.com",
    previousLate: 2,
    paymentHistory: [
      { month: "May 2026", amount: 1650, date: "5 May 2026", status: "Paid", daysLate: 4 },
      { month: "Apr 2026", amount: 1650, date: "1 Apr 2026", status: "Paid", daysLate: 0 },
      { month: "Mar 2026", amount: 1650, date: "3 Mar 2026", status: "Paid", daysLate: 2 },
    ],
    communications: [
      { date: "4 Jun 2026", type: "SMS", subject: "Rent overdue — please arrange payment", status: "Sent", agent: "Sarah Cooper" },
      { date: "1 Jun 2026", type: "Email", subject: "Rent Due — June 2026", status: "Sent", agent: "Auto" },
    ],
  },
  {
    id: 3,
    property: "Flat 7 Park View",
    tenant: "Lisa Chen",
    landlord: "David Thompson",
    rentAmount: 1200,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 3600,
    arrearsMonths: 3,
    totalArrears: 3600,
    riskRating: "High",
    lastContact: "3 Jun 2026",
    contactMethod: "Formal Warning Letter",
    tenantPhone: "+44 7700 900789",
    tenantEmail: "lisa.chen@email.com",
    previousLate: 4,
    paymentHistory: [
      { month: "May 2026", amount: 1200, date: null, status: "Unpaid", daysLate: 0 },
      { month: "Apr 2026", amount: 1200, date: "10 Apr 2026", status: "Paid", daysLate: 9 },
      { month: "Mar 2026", amount: 1200, date: "5 Mar 2026", status: "Paid", daysLate: 4 },
      { month: "Feb 2026", amount: 1200, date: "2 Feb 2026", status: "Paid", daysLate: 1 },
    ],
    communications: [
      { date: "3 Jun 2026", type: "Letter", subject: "Formal Warning — Rent Arrears", status: "Sent", agent: "Tom Wilson" },
      { date: "1 Jun 2026", type: "SMS", subject: "Urgent: Rent arrears £3,600", status: "Sent", agent: "Sarah Cooper" },
      { date: "28 May 2026", type: "Email", subject: "Second Reminder — May 2026 Rent", status: "Sent", agent: "Sarah Cooper" },
      { date: "15 May 2026", type: "Email", subject: "First Reminder — May 2026 Rent", status: "Sent", agent: "Auto" },
      { date: "1 May 2026", type: "Email", subject: "Rent Due — May 2026", status: "Sent", agent: "Auto" },
    ],
  },
  {
    id: 4,
    property: "Flat 4B Oak Street",
    tenant: "Sarah Jenkins",
    landlord: "David Thompson",
    rentAmount: 950,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 950,
    arrearsMonths: 1,
    totalArrears: 950,
    riskRating: "Low",
    lastContact: "6 Jun 2026",
    contactMethod: "Email Reminder",
    tenantPhone: "+44 7700 900321",
    tenantEmail: "sarah.jenkins@email.com",
    previousLate: 1,
    paymentHistory: [
      { month: "May 2026", amount: 950, date: "2 May 2026", status: "Paid", daysLate: 1 },
      { month: "Apr 2026", amount: 950, date: "1 Apr 2026", status: "Paid", daysLate: 0 },
    ],
    communications: [
      { date: "6 Jun 2026", type: "Email", subject: "Friendly Reminder — June 2026 Rent", status: "Sent", agent: "Auto" },
    ],
  },
  {
    id: 5,
    property: "45 Baker Street",
    tenant: "Emily Carter",
    landlord: "Sarah Walker",
    rentAmount: 2100,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 2100,
    arrearsMonths: 1,
    totalArrears: 2100,
    riskRating: "Medium",
    lastContact: "5 Jun 2026",
    contactMethod: "Phone Call",
    tenantPhone: "+44 7700 900654",
    tenantEmail: "emily.carter@email.com",
    previousLate: 3,
    paymentHistory: [
      { month: "May 2026", amount: 2100, date: "6 May 2026", status: "Paid", daysLate: 5 },
      { month: "Apr 2026", amount: 2100, date: "4 Apr 2026", status: "Paid", daysLate: 3 },
      { month: "Mar 2026", amount: 2100, date: "2 Mar 2026", status: "Paid", daysLate: 1 },
    ],
    communications: [
      { date: "5 Jun 2026", type: "Phone", subject: "Phone call — payment arrangement", status: "Completed", agent: "Sarah Cooper" },
      { date: "1 Jun 2026", type: "Email", subject: "Rent Due — June 2026", status: "Sent", agent: "Auto" },
    ],
  },
  {
    id: 6,
    property: "Unit 3 Riverside Court",
    tenant: "Emma Wilson",
    landlord: "James Richardson",
    rentAmount: 1400,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 4200,
    arrearsMonths: 3,
    totalArrears: 4200,
    riskRating: "High",
    lastContact: "2 Jun 2026",
    contactMethod: "Formal Warning Letter",
    tenantPhone: "+44 7700 900987",
    tenantEmail: "emma.wilson@email.com",
    previousLate: 5,
    paymentHistory: [
      { month: "May 2026", amount: 1400, date: null, status: "Unpaid", daysLate: 0 },
      { month: "Apr 2026", amount: 1400, date: "12 Apr 2026", status: "Paid", daysLate: 11 },
      { month: "Mar 2026", amount: 1400, date: "8 Mar 2026", status: "Paid", daysLate: 7 },
    ],
    communications: [
      { date: "2 Jun 2026", type: "Letter", subject: "Formal Notice — Rent Arrears", status: "Sent", agent: "Tom Wilson" },
      { date: "1 Jun 2026", type: "SMS", subject: "Urgent: Rent arrears £4,200", status: "Sent", agent: "Auto" },
      { date: "28 May 2026", type: "Email", subject: "Second Reminder — May 2026", status: "Sent", agent: "Sarah Cooper" },
    ],
  },
  {
    id: 7,
    property: "21 High Street",
    tenant: "Robert Green",
    landlord: "Robert Stewart",
    rentAmount: 800,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 800,
    arrearsMonths: 1,
    totalArrears: 800,
    riskRating: "Low",
    lastContact: "6 Jun 2026",
    contactMethod: "Email Reminder",
    tenantPhone: "+44 7700 900147",
    tenantEmail: "robert.green@email.com",
    previousLate: 0,
    paymentHistory: [
      { month: "May 2026", amount: 800, date: "1 May 2026", status: "Paid", daysLate: 0 },
      { month: "Apr 2026", amount: 800, date: "1 Apr 2026", status: "Paid", daysLate: 0 },
    ],
    communications: [
      { date: "6 Jun 2026", type: "Email", subject: "Rent Reminder — June 2026", status: "Sent", agent: "Auto" },
    ],
  },
  {
    id: 8,
    property: "34 Maple Gardens",
    tenant: "David Thompson",
    landlord: "Sarah Walker",
    rentAmount: 2400,
    dueDate: "1 Jun 2026",
    paidDate: null,
    outstanding: 4800,
    arrearsMonths: 2,
    totalArrears: 4800,
    riskRating: "High",
    lastContact: "3 Jun 2026",
    contactMethod: "Formal Warning Letter",
    tenantPhone: "+44 7700 900258",
    tenantEmail: "david.thompson@email.com",
    previousLate: 3,
    paymentHistory: [
      { month: "May 2026", amount: 2400, date: null, status: "Unpaid", daysLate: 0 },
      { month: "Apr 2026", amount: 2400, date: "7 Apr 2026", status: "Paid", daysLate: 6 },
      { month: "Mar 2026", amount: 2400, date: "3 Mar 2026", status: "Paid", daysLate: 2 },
    ],
    communications: [
      { date: "3 Jun 2026", type: "Letter", subject: "Formal Warning — Rent Arrears", status: "Sent", agent: "Tom Wilson" },
      { date: "1 Jun 2026", type: "SMS", subject: "Urgent: Rent arrears £4,800", status: "Sent", agent: "Auto" },
      { date: "28 May 2026", type: "Email", subject: "Second Reminder — May 2026", status: "Sent", agent: "Sarah Cooper" },
    ],
  },
];

export const agentActions = [
  { id: 1, date: "6 Jun 2026", time: "14:30", agent: "Sarah Cooper", action: "Sent email reminder", tenant: "John Miller", property: "12 Rose Avenue", outcome: "Sent" },
  { id: 2, date: "6 Jun 2026", time: "13:15", agent: "Sarah Cooper", action: "Sent email reminder", tenant: "Sarah Jenkins", property: "Flat 4B Oak Street", outcome: "Sent" },
  { id: 3, date: "6 Jun 2026", time: "11:00", agent: "Sarah Cooper", action: "Sent email reminder", tenant: "Robert Green", property: "21 High Street", outcome: "Sent" },
  { id: 4, date: "5 Jun 2026", time: "16:45", agent: "Sarah Cooper", action: "Phone call follow-up", tenant: "Emily Carter", property: "45 Baker Street", outcome: "Payment arrangement agreed" },
  { id: 5, date: "5 Jun 2026", time: "10:20", agent: "Sarah Cooper", action: "Sent SMS reminder", tenant: "Michael Brown", property: "8 The Crescent", outcome: "Sent" },
  { id: 6, date: "4 Jun 2026", time: "09:00", agent: "Tom Wilson", action: "Issued formal warning letter", tenant: "Lisa Chen", property: "Flat 7 Park View", outcome: "Sent via post & email" },
  { id: 7, date: "3 Jun 2026", time: "15:30", agent: "Tom Wilson", action: "Issued formal warning letter", tenant: "Emma Wilson", property: "Unit 3 Riverside Court", outcome: "Sent via post & email" },
  { id: 8, date: "3 Jun 2026", time: "14:00", agent: "Tom Wilson", action: "Issued formal warning letter", tenant: "David Thompson", property: "34 Maple Gardens", outcome: "Sent via post & email" },
  { id: 9, date: "2 Jun 2026", time: "11:30", agent: "Sarah Cooper", action: "Sent SMS reminder", tenant: "Lisa Chen", property: "Flat 7 Park View", outcome: "Sent" },
  { id: 10, date: "1 Jun 2026", time: "09:00", agent: "Auto", action: "Automated due date reminders", tenant: "All tenants", property: "Multiple", outcome: "8 emails sent" },
];

export const paymentPlans = [
  {
    id: 1,
    tenant: "Lisa Chen",
    property: "Flat 7 Park View",
    totalArrears: 3600,
    monthlyRent: 1200,
    plan: [
      { date: "15 Jun 2026", amount: 1200, type: "Rent", status: "Scheduled" },
      { date: "15 Jun 2026", amount: 400, type: "Arrears", status: "Scheduled" },
      { date: "1 Jul 2026", amount: 1200, type: "Rent", status: "Scheduled" },
      { date: "15 Jul 2026", amount: 400, type: "Arrears", status: "Scheduled" },
      { date: "1 Aug 2026", amount: 1200, type: "Rent", status: "Scheduled" },
      { date: "15 Aug 2026", amount: 400, type: "Arrears", status: "Scheduled" },
      { date: "1 Sep 2026", amount: 1200, type: "Rent", status: "Scheduled" },
      { date: "15 Sep 2026", amount: 400, type: "Arrears", status: "Scheduled" },
      { date: "1 Oct 2026", amount: 1200, type: "Rent", status: "Scheduled" },
      { date: "15 Oct 2026", amount: 400, type: "Arrears", status: "Scheduled" },
    ],
    createdBy: "Tom Wilson",
    createdDate: "3 Jun 2026",
    status: "Active",
  },
  {
    id: 2,
    tenant: "Emma Wilson",
    property: "Unit 3 Riverside Court",
    totalArrears: 4200,
    monthlyRent: 1400,
    plan: [
      { date: "10 Jun 2026", amount: 1400, type: "Rent", status: "Scheduled" },
      { date: "10 Jun 2026", amount: 700, type: "Arrears", status: "Scheduled" },
      { date: "1 Jul 2026", amount: 1400, type: "Rent", status: "Scheduled" },
      { date: "10 Jul 2026", amount: 700, type: "Arrears", status: "Scheduled" },
      { date: "1 Aug 2026", amount: 1400, type: "Rent", status: "Scheduled" },
      { date: "10 Aug 2026", amount: 700, type: "Arrears", status: "Scheduled" },
      { date: "1 Sep 2026", amount: 1400, type: "Rent", status: "Scheduled" },
      { date: "10 Sep 2026", amount: 700, type: "Arrears", status: "Scheduled" },
      { date: "1 Oct 2026", amount: 1400, type: "Rent", status: "Scheduled" },
      { date: "10 Oct 2026", amount: 700, type: "Arrears", status: "Scheduled" },
    ],
    createdBy: "Tom Wilson",
    createdDate: "2 Jun 2026",
    status: "Active",
  },
];

export const riskConfig: Record<string, { badge: string; bg: string; text: string; border: string; icon: string }> = {
  Low: {
    badge: "bg-[#10B981]/10 text-[#10B981]",
    bg: "bg-[#10B981]/10",
    text: "text-[#10B981]",
    border: "border-[#10B981]/20",
    icon: "ri-shield-check-line",
  },
  Medium: {
    badge: "bg-[#F59E0B]/10 text-[#F59E0B]",
    bg: "bg-[#F59E0B]/10",
    text: "text-[#F59E0B]",
    border: "border-[#F59E0B]/20",
    icon: "ri-alert-line",
  },
  High: {
    badge: "bg-[#EF4444]/10 text-[#EF4444]",
    bg: "bg-[#EF4444]/10",
    text: "text-[#EF4444]",
    border: "border-[#EF4444]/20",
    icon: "ri-alarm-warning-line",
  },
};