export interface PaymentRecord {
  id: string
  propertyName: string
  propertyId: string
  tenantName: string
  tenantId: string
  tenancyRef: string
  tenancyId: string
  ownerName: string
  amountDue: number
  amountPaid: number
  outstanding: number
  paymentDate: string | null
  paymentMethod: string
  reference: string
  status: "due" | "paid" | "part_paid" | "partial" | "overdue" | "failed" | "refunded" | "waived"
  month: string
  notes: string
  hasReceipt: boolean
}

export const payments: PaymentRecord[] = [
  {
    id: "pmt-001",
    propertyName: "12 Rose Avenue",
    propertyId: "1",
    tenantName: "John Miller",
    tenantId: "tnt-001",
    tenancyRef: "TNCY-2024-001",
    tenancyId: "tncy-001",
    ownerName: "James Richardson",
    amountDue: 1850,
    amountPaid: 1850,
    outstanding: 0,
    paymentDate: "01 Jun 2026",
    paymentMethod: "Bank Transfer",
    reference: "Rent Jun 2026 Rose Ave",
    status: "paid",
    month: "Jun 2026",
    notes: "",
    hasReceipt: true,
  },
  {
    id: "pmt-002",
    propertyName: "Flat 4B Oak Street",
    propertyId: "2",
    tenantName: "Sarah Jenkins",
    tenantId: "tnt-002",
    tenancyRef: "TNCY-2025-002",
    tenancyId: "tncy-002",
    ownerName: "David Thompson",
    amountDue: 950,
    amountPaid: 950,
    outstanding: 0,
    paymentDate: "03 Jun 2026",
    paymentMethod: "Direct Debit",
    reference: "DD Oak St Jun",
    status: "paid",
    month: "Jun 2026",
    notes: "Late by 2 days",
    hasReceipt: true,
  },
  {
    id: "pmt-003",
    propertyName: "45 Baker Street",
    propertyId: "3",
    tenantName: "Emily Carter",
    tenantId: "tnt-003",
    tenancyRef: "TNCY-2025-003",
    tenancyId: "tncy-003",
    ownerName: "Sarah Walker",
    amountDue: 2100,
    amountPaid: 0,
    outstanding: 2100,
    paymentDate: null,
    paymentMethod: "",
    reference: "",
    status: "due",
    month: "Jun 2026",
    notes: "Due 1st June — reminder sent 5 Jun",
    hasReceipt: false,
  },
  {
    id: "pmt-004",
    propertyName: "8 The Crescent",
    propertyId: "4",
    tenantName: "Michael Brown",
    tenantId: "tnt-004",
    tenancyRef: "TNCY-2024-004",
    tenancyId: "tncy-004",
    ownerName: "Margaret Hughes",
    amountDue: 1650,
    amountPaid: 0,
    outstanding: 1650,
    paymentDate: null,
    paymentMethod: "",
    reference: "",
    status: "overdue",
    month: "Jun 2026",
    notes: "Overdue since 1 Jun — SMS reminder sent",
    hasReceipt: false,
  },
  {
    id: "pmt-005",
    propertyName: "34 Maple Gardens",
    propertyId: "5",
    tenantName: "David Thompson",
    tenantId: "tnt-005",
    tenancyRef: "TNCY-2024-005",
    tenancyId: "tncy-005",
    ownerName: "Sarah Walker",
    amountDue: 2400,
    amountPaid: 2400,
    outstanding: 0,
    paymentDate: "01 Jun 2026",
    paymentMethod: "Standing Order",
    reference: "SO Maple Gdns",
    status: "paid",
    month: "Jun 2026",
    notes: "",
    hasReceipt: true,
  },
  {
    id: "pmt-006",
    propertyName: "Flat 7 Park View",
    propertyId: "6",
    tenantName: "Lisa Chen",
    tenantId: "tnt-006",
    tenancyRef: "TNCY-2025-006",
    tenancyId: "tncy-006",
    ownerName: "David Thompson",
    amountDue: 1200,
    amountPaid: 0,
    outstanding: 3600,
    paymentDate: null,
    paymentMethod: "",
    reference: "",
    status: "overdue",
    month: "Jun 2026",
    notes: "3 months in arrears — formal warning issued",
    hasReceipt: false,
  },
  {
    id: "pmt-007",
    propertyName: "21 High Street",
    propertyId: "7",
    tenantName: "Robert Green",
    tenantId: "tnt-007",
    tenancyRef: "TNCY-2025-007",
    tenancyId: "tncy-007",
    ownerName: "Robert Stewart",
    amountDue: 800,
    amountPaid: 0,
    outstanding: 800,
    paymentDate: null,
    paymentMethod: "",
    reference: "",
    status: "due",
    month: "Jun 2026",
    notes: "Due 1st June",
    hasReceipt: false,
  },
  {
    id: "pmt-008",
    propertyName: "Unit 3 Riverside Court",
    propertyId: "8",
    tenantName: "Emma Wilson",
    tenantId: "tnt-008",
    tenancyRef: "TNCY-2024-008",
    tenancyId: "tncy-008",
    ownerName: "James Richardson",
    amountDue: 1400,
    amountPaid: 1400,
    outstanding: 0,
    paymentDate: "01 Jun 2026",
    paymentMethod: "Bank Transfer",
    reference: "Rent Riverside Jun",
    status: "paid",
    month: "Jun 2026",
    notes: "",
    hasReceipt: true,
  },
  {
    id: "pmt-009",
    propertyName: "12 Rose Avenue",
    propertyId: "1",
    tenantName: "John Miller",
    tenantId: "tnt-001",
    tenancyRef: "TNCY-2024-001",
    tenancyId: "tncy-001",
    ownerName: "James Richardson",
    amountDue: 1850,
    amountPaid: 1850,
    outstanding: 0,
    paymentDate: "01 May 2026",
    paymentMethod: "Bank Transfer",
    reference: "Rent May 2026 Rose Ave",
    status: "paid",
    month: "May 2026",
    notes: "",
    hasReceipt: true,
  },
  {
    id: "pmt-010",
    propertyName: "8 The Crescent",
    propertyId: "4",
    tenantName: "Michael Brown",
    tenantId: "tnt-004",
    tenancyRef: "TNCY-2024-004",
    tenancyId: "tncy-004",
    ownerName: "Margaret Hughes",
    amountDue: 1650,
    amountPaid: 1650,
    outstanding: 0,
    paymentDate: "05 May 2026",
    paymentMethod: "Standing Order",
    reference: "SO Crescent May",
    status: "paid",
    month: "May 2026",
    notes: "Late by 4 days",
    hasReceipt: true,
  },
  {
    id: "pmt-011",
    propertyName: "Flat 7 Park View",
    propertyId: "6",
    tenantName: "Lisa Chen",
    tenantId: "tnt-006",
    tenancyRef: "TNCY-2025-006",
    tenancyId: "tncy-006",
    ownerName: "David Thompson",
    amountDue: 1200,
    amountPaid: 0,
    outstanding: 2400,
    paymentDate: null,
    paymentMethod: "",
    reference: "",
    status: "overdue",
    month: "May 2026",
    notes: "Unpaid — carried forward",
    hasReceipt: false,
  },
  {
    id: "pmt-012",
    propertyName: "34 Maple Gardens",
    propertyId: "5",
    tenantName: "David Thompson",
    tenantId: "tnt-005",
    tenancyRef: "TNCY-2024-005",
    tenancyId: "tncy-005",
    ownerName: "Sarah Walker",
    amountDue: 2400,
    amountPaid: 1200,
    outstanding: 1200,
    paymentDate: "15 May 2026",
    paymentMethod: "Bank Transfer",
    reference: "Part payment Maple",
    status: "part_paid",
    month: "May 2026",
    notes: "Partial payment — £1,200 outstanding",
    hasReceipt: true,
  },
]

export const paymentStatusBadge: Record<string, string> = {
  due: "bg-[#3B82F6]/10 text-[#3B82F6]",
  paid: "bg-[#10B981]/10 text-[#10B981]",
  part_paid: "bg-[#F59E0B]/10 text-[#F59E0B]",
  overdue: "bg-[#EF4444]/10 text-[#EF4444]",
  waived: "bg-[#94A3B8]/10 text-[#94A3B8]",
}

export const paymentStatusLabel: Record<string, string> = {
  due: "Due",
  paid: "Paid",
  part_paid: "Part Paid",
  overdue: "Overdue",
  waived: "Waived",
}

export const paymentStatusIcon: Record<string, string> = {
  due: "ri-time-line",
  paid: "ri-check-double-line",
  part_paid: "ri-check-line",
  overdue: "ri-alarm-warning-line",
  waived: "ri-close-circle-line",
}

export const paymentMethods = [
  "Bank Transfer",
  "Direct Debit",
  "Standing Order",
  "Cash",
  "Card",
  "Cheque",
]