export interface MarketplaceContractor {
  id: string;
  companyName: string;
  trade: string;
  contactName: string;
  email: string;
  phone: string;
  rating: number;
  totalJobs: number;
  completedJobs: number;
  responseTimeHours: number;
  onTimeRate: number;
  hourlyRate: number;
  avgQuoteAmount: number;
  status: "active" | "inactive" | "pending";
  serviceAreas: string[];
  insurance: { type: string; provider: string; expiry: string; status: string; coverAmount: string }[];
  certifications: { name: string; issuer: string; date: string; expiry: string; status: string }[];
  reviews: { reviewer: string; date: string; rating: number; text: string; jobType: string }[];
  recentJobs: { title: string; property: string; amount: number; date: string; status: string }[];
  bio: string;
  memberSince: string;
  paymentTerms: string;
  emergencyCallout: boolean;
  emergencyFee: string;
  avatar: string;
  available: boolean;
  vatNumber: string;
  companyNumber: string;
}

export const serviceCategories = [
  { key: "all", label: "All Trades", icon: "ri-building-4-line" },
  { key: "electrician", label: "Electrician", icon: "ri-flashlight-line" },
  { key: "plumber", label: "Plumber", icon: "ri-drop-line" },
  { key: "gas_engineer", label: "Gas Engineer", icon: "ri-fire-line" },
  { key: "locksmith", label: "Locksmith", icon: "ri-key-2-line" },
  { key: "roofer", label: "Roofer", icon: "ri-home-3-line" },
  { key: "builder", label: "Builder", icon: "ri-hammer-line" },
  { key: "handyman", label: "Handyman", icon: "ri-tools-line" },
  { key: "decorator", label: "Decorator", icon: "ri-paint-brush-line" },
  { key: "cleaner", label: "Cleaner", icon: "ri-shining-line" },
  { key: "inventory_clerk", label: "Inventory Clerk", icon: "ri-clipboard-line" },
  { key: "epc_assessor", label: "EPC Assessor", icon: "ri-file-chart-line" },
  { key: "eicr_contractor", label: "EICR Contractor", icon: "ri-shield-flash-line" },
  { key: "fire_safety", label: "Fire Safety", icon: "ri-alarm-warning-line" },
  { key: "damp_mould", label: "Damp & Mould", icon: "ri-contrast-drop-line" },
];

export const marketplaceContractors: MarketplaceContractor[] = [
  {
    id: "mc-1",
    companyName: "GreenPlumb Ltd",
    trade: "Plumber",
    contactName: "David Green",
    email: "jobs@greenplumb.co.uk",
    phone: "020 7946 0958",
    rating: 4.9,
    totalJobs: 48,
    completedJobs: 45,
    responseTimeHours: 2.3,
    onTimeRate: 94,
    hourlyRate: 65,
    avgQuoteAmount: 185,
    status: "active",
    serviceAreas: ["London", "Bristol", "Cardiff", "Birmingham"],
    insurance: [
      { type: "Public Liability", provider: "AXA Insurance", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Employers Liability", provider: "AXA Insurance", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "Gas Safe Registered", issuer: "Gas Safe Register", date: "15 Mar 2026", expiry: "14 Mar 2027", status: "Valid" },
      { name: "WaterSafe Approved", issuer: "WaterSafe", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
    ],
    reviews: [
      { reviewer: "Sarah Collins", date: "22 May 2026", rating: 5, text: "Excellent work, very tidy and professional. Tenant very happy.", jobType: "Radiator Repair" },
      { reviewer: "James Hart", date: "18 May 2026", rating: 4, text: "Good work, slightly delayed but quality was high.", jobType: "Extractor Fan" },
      { reviewer: "Sarah Collins", date: "15 May 2026", rating: 5, text: "Quick fix, tenant very satisfied. Arrived on time.", jobType: "Lock Repair" },
    ],
    recentJobs: [
      { title: "Boiler pressure loss", property: "Rose Court Flat 2A", amount: 336, date: "26 May 2026", status: "Quoted" },
      { title: "Leaking kitchen tap", property: "Riverside Court", amount: 114, date: "19 May 2026", status: "Approved" },
      { title: "Radiator not heating", property: "Rose Court Flat 2A", amount: 222, date: "21 May 2026", status: "Completed" },
    ],
    bio: "Professional plumbing and heating company serving London and the South East. Specialising in emergency repairs, boiler installations, and full bathroom refurbishments.",
    memberSince: "Mar 2023",
    paymentTerms: "14 days",
    emergencyCallout: true,
    emergencyFee: "£95 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20plumber%20contractor%20headshot%20portrait%20smiling%20warmly%2C%20wearing%20navy%20blue%20work%20polo%20shirt%20with%20company%20logo%2C%20clean%20white%20studio%20background%2C%20professional%20corporate%20photography%2C%20soft%20diffused%20lighting%2C%20confident%20friendly%20expression%2C%20sharp%20focus%20on%20face&width=200&height=200&seq=1&orientation=squarish",
    available: true,
    vatNumber: "GB123456789",
    companyNumber: "09876543",
  },
  {
    id: "mc-2",
    companyName: "Bright Spark Electrical",
    trade: "Electrician",
    contactName: "Mark Jennings",
    email: "jobs@brightspark.co.uk",
    phone: "0161 555 0199",
    rating: 4.7,
    totalJobs: 32,
    completedJobs: 30,
    responseTimeHours: 4.1,
    onTimeRate: 89,
    hourlyRate: 75,
    avgQuoteAmount: 245,
    status: "active",
    serviceAreas: ["Manchester", "Liverpool", "Leeds"],
    insurance: [
      { type: "Public Liability", provider: "Aviva", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Employers Liability", provider: "Aviva", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "NICEIC Approved Contractor", issuer: "NICEIC", date: "10 Feb 2026", expiry: "09 Feb 2027", status: "Valid" },
      { name: "Part P Registered", issuer: "NICEIC", date: "01 Mar 2026", expiry: "28 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "Sarah Collins", date: "15 May 2026", rating: 5, text: "Arrived on time and solved the problem in minutes.", jobType: "Extractor Fan" },
      { reviewer: "James Hart", date: "28 Apr 2026", rating: 4, text: "Good work but quote was a bit higher than expected.", jobType: "Rewiring" },
    ],
    recentJobs: [
      { title: "Bathroom extractor fan", property: "Rose Court Flat 2A", amount: 174, date: "16 May 2026", status: "Completed" },
      { title: "Full rewiring", property: "Riverside Court", amount: 3840, date: "20 Apr 2026", status: "Quoted" },
    ],
    bio: "Fully qualified electrical contractors for domestic and commercial properties. EICR certificates, rewiring, and emergency electrical repairs.",
    memberSince: "Jun 2024",
    paymentTerms: "30 days",
    emergencyCallout: true,
    emergencyFee: "£120 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20electrician%20contractor%20headshot%20portrait%2C%20wearing%20grey%20work%20shirt%2C%20friendly%20confident%20smile%2C%20clean%20studio%20background%2C%20professional%20corporate%20photography%2C%20soft%20lighting%2C%20sharp%20focus&width=200&height=200&seq=2&orientation=squarish",
    available: true,
    vatNumber: "GB987654321",
    companyNumber: "12345678",
  },
  {
    id: "mc-3",
    companyName: "GasSafe Pro Solutions",
    trade: "Gas Engineer",
    contactName: "Robert Clarke",
    email: "info@gassafepro.co.uk",
    phone: "0121 555 0300",
    rating: 4.8,
    totalJobs: 56,
    completedJobs: 52,
    responseTimeHours: 1.8,
    onTimeRate: 96,
    hourlyRate: 85,
    avgQuoteAmount: 220,
    status: "active",
    serviceAreas: ["Birmingham", "Coventry", "Wolverhampton", "Solihull"],
    insurance: [
      { type: "Public Liability", provider: "Zurich", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Employers Liability", provider: "Zurich", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "Gas Safe Registered", issuer: "Gas Safe Register", date: "01 Apr 2026", expiry: "31 Mar 2027", status: "Valid" },
      { name: "OFTEC Registered", issuer: "OFTEC", date: "15 Jan 2026", expiry: "14 Jan 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "10 Jun 2026", rating: 5, text: "Incredibly fast response. Fixed our boiler same day.", jobType: "Boiler Repair" },
      { reviewer: "Sarah Collins", date: "02 Jun 2026", rating: 5, text: "Annual gas safety check completed thoroughly. Certificate issued same day.", jobType: "Gas Safety Check" },
      { reviewer: "James Hart", date: "20 May 2026", rating: 4, text: "Good work. Slight delay with paperwork.", jobType: "Boiler Service" },
    ],
    recentJobs: [
      { title: "Boiler replacement", property: "Maple Gardens House", amount: 2850, date: "10 Jun 2026", status: "Completed" },
      { title: "Gas safety check", property: "Rose Court Flat 2A", amount: 95, date: "02 Jun 2026", status: "Completed" },
      { title: "Boiler service", property: "Riverside Court", amount: 120, date: "20 May 2026", status: "Completed" },
    ],
    bio: "Specialist gas engineering company. Landlord gas safety certificates, boiler installation and repair, central heating systems. 24/7 emergency response.",
    memberSince: "Jan 2022",
    paymentTerms: "14 days",
    emergencyCallout: true,
    emergencyFee: "£110 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20gas%20engineer%20headshot%20portrait%2C%20wearing%20navy%20blue%20uniform%20with%20gas%20safe%20badge%2C%20warm%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20corporate%20photography%2C%20soft%20lighting&width=200&height=200&seq=3&orientation=squarish",
    available: true,
    vatNumber: "GB456789123",
    companyNumber: "09876123",
  },
  {
    id: "mc-4",
    companyName: "SecureFix Locksmiths",
    trade: "Locksmith",
    contactName: "Tony Reeves",
    email: "info@securefix.co.uk",
    phone: "0121 496 0358",
    rating: 4.8,
    totalJobs: 21,
    completedJobs: 19,
    responseTimeHours: 1.5,
    onTimeRate: 96,
    hourlyRate: 55,
    avgQuoteAmount: 95,
    status: "active",
    serviceAreas: ["Birmingham", "Coventry", "Wolverhampton"],
    insurance: [
      { type: "Public Liability", provider: "Zurich", expiry: "28 Feb 2027", status: "Valid", coverAmount: "£5,000,000" },
    ],
    certifications: [
      { name: "Master Locksmith Association", issuer: "MLA", date: "20 Jan 2026", expiry: "19 Jan 2027", status: "Valid" },
      { name: "Security Industry Authority", issuer: "SIA", date: "05 Feb 2026", expiry: "04 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "10 May 2026", rating: 5, text: "Arrived within 20 minutes. Tenant locked out — sorted immediately.", jobType: "Emergency Entry" },
      { reviewer: "Sarah Collins", date: "05 May 2026", rating: 5, text: "Fast, efficient, and fair pricing. Changed all locks after tenancy change.", jobType: "Lock Change" },
    ],
    recentJobs: [
      { title: "Front door lock sticking", property: "Rose Court Flat 2A", amount: 78, date: "11 May 2026", status: "Completed" },
      { title: "Garden gate hinge", property: "Maple Gardens House", amount: 54, date: "27 May 2026", status: "Assigned" },
    ],
    bio: "24/7 locksmith and security services. Emergency entry, lock changes, security upgrades for rental properties. All work guaranteed.",
    memberSince: "Sep 2024",
    paymentTerms: "14 days",
    emergencyCallout: true,
    emergencyFee: "£75 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20locksmith%20headshot%20portrait%2C%20wearing%20dark%20uniform%2C%20friendly%20confident%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20corporate%20photography%2C%20sharp%20detail%2C%20soft%20diffused%20lighting&width=200&height=200&seq=4&orientation=squarish",
    available: true,
    vatNumber: "GB321654987",
    companyNumber: "87654321",
  },
  {
    id: "mc-5",
    companyName: "Summit Roofing Ltd",
    trade: "Roofer",
    contactName: "Kevin Bridges",
    email: "hello@summitroofing.co.uk",
    phone: "0113 555 0450",
    rating: 4.6,
    totalJobs: 43,
    completedJobs: 39,
    responseTimeHours: 8.5,
    onTimeRate: 82,
    hourlyRate: 60,
    avgQuoteAmount: 1850,
    status: "active",
    serviceAreas: ["Leeds", "Sheffield", "York", "Bradford"],
    insurance: [
      { type: "Public Liability", provider: "NFU Mutual", expiry: "15 Aug 2027", status: "Valid", coverAmount: "£10,000,000" },
      { type: "Employers Liability", provider: "NFU Mutual", expiry: "15 Aug 2027", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "NFRC Member", issuer: "NFRC", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
      { name: "CSCS Gold", issuer: "CSCS", date: "01 Mar 2026", expiry: "28 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "05 May 2026", rating: 4, text: "Good roof repair. Took a few days longer than quoted but quality was excellent.", jobType: "Roof Repair" },
      { reviewer: "Sarah Collins", date: "12 Apr 2026", rating: 5, text: "Full roof replacement completed on schedule. Very professional team.", jobType: "Roof Replacement" },
    ],
    recentJobs: [
      { title: "Flat roof repair", property: "Riverside Court", amount: 2200, date: "05 May 2026", status: "Completed" },
      { title: "Roof inspection", property: "Maple Gardens House", amount: 350, date: "20 Apr 2026", status: "Completed" },
    ],
    bio: "Specialist roofing contractors covering all types of roofing work. Flat roofs, pitched roofs, repairs, and full replacements. 15 years experience.",
    memberSince: "Mar 2022",
    paymentTerms: "30 days",
    emergencyCallout: true,
    emergencyFee: "£150 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20roofer%20headshot%20portrait%2C%20wearing%20an%20orange%20hi-vis%20vest%20over%20a%20polo%20shirt%2C%20friendly%20confident%20smile%2C%20clean%20studio%20background%2C%20professional%20corporate%20photography%2C%20soft%20lighting&width=200&height=200&seq=5&orientation=squarish",
    available: true,
    vatNumber: "GB654987321",
    companyNumber: "54321098",
  },
  {
    id: "mc-6",
    companyName: "BuildRight Construction",
    trade: "Builder",
    contactName: "Paul Mason",
    email: "hello@buildright.co.uk",
    phone: "020 7946 0234",
    rating: 4.5,
    totalJobs: 67,
    completedJobs: 61,
    responseTimeHours: 8.5,
    onTimeRate: 82,
    hourlyRate: 55,
    avgQuoteAmount: 1850,
    status: "active",
    serviceAreas: ["London", "Essex", "Kent"],
    insurance: [
      { type: "Public Liability", provider: "Allianz", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£10,000,000" },
      { type: "Employers Liability", provider: "Allianz", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "CSCS Gold", issuer: "CSCS", date: "15 Mar 2026", expiry: "14 Mar 2027", status: "Valid" },
      { name: "CHAS Accredited", issuer: "CHAS", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
    ],
    reviews: [
      { reviewer: "Sarah Collins", date: "01 May 2026", rating: 4, text: "Good builders but project took longer than quoted. Final result excellent.", jobType: "Kitchen Renovation" },
      { reviewer: "James Hart", date: "15 Apr 2026", rating: 4, text: "Solid work. Competitive quote and professional team.", jobType: "Bathroom Refurb" },
    ],
    recentJobs: [
      { title: "Kitchen renovation", property: "Maple Gardens House", amount: 5040, date: "01 May 2026", status: "In Progress" },
      { title: "Bathroom refurb", property: "Riverside Court", amount: 3360, date: "15 Apr 2026", status: "Completed" },
    ],
    bio: "Full-service building company specialising in renovations, extensions, and maintenance. 15 years working with letting agents and landlords.",
    memberSince: "Jan 2022",
    paymentTerms: "30 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20builder%20headshot%20portrait%2C%20wearing%20orange%20hi-vis%20vest%2C%20confident%20friendly%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20photography%2C%20sharp%20focus%2C%20soft%20lighting&width=200&height=200&seq=6&orientation=squarish",
    available: true,
    vatNumber: "GB789123456",
    companyNumber: "65432109",
  },
  {
    id: "mc-7",
    companyName: "FixIt Handyman Services",
    trade: "Handyman",
    contactName: "Steve Miller",
    email: "steve@fixithandy.co.uk",
    phone: "0161 555 0720",
    rating: 4.5,
    totalJobs: 89,
    completedJobs: 84,
    responseTimeHours: 3.2,
    onTimeRate: 91,
    hourlyRate: 40,
    avgQuoteAmount: 120,
    status: "active",
    serviceAreas: ["Manchester", "Stockport", "Bolton", "Oldham"],
    insurance: [
      { type: "Public Liability", provider: "Direct Line", expiry: "15 Mar 2027", status: "Valid", coverAmount: "£2,000,000" },
    ],
    certifications: [],
    reviews: [
      { reviewer: "Sarah Collins", date: "08 Jun 2026", rating: 5, text: "Fixed multiple small issues across three properties in one day. Amazing value.", jobType: "General Repairs" },
      { reviewer: "James Hart", date: "25 May 2026", rating: 4, text: "Good all-round handyman. Sorted everything from shelving to door handles.", jobType: "Property Maintenance" },
      { reviewer: "Sarah Collins", date: "10 May 2026", rating: 5, text: "Quick, tidy, and reasonably priced. Will definitely use again.", jobType: "Furniture Assembly" },
    ],
    recentJobs: [
      { title: "Multiple property fixes", property: "Rose Court Flats", amount: 280, date: "08 Jun 2026", status: "Completed" },
      { title: "Door handle replacement", property: "Riverside Court", amount: 65, date: "25 May 2026", status: "Completed" },
    ],
    bio: "Reliable handyman service for all those small but essential property repairs. From fixing doors to assembling furniture — no job too small.",
    memberSince: "Aug 2023",
    paymentTerms: "7 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20handyman%20headshot%20portrait%2C%20wearing%20casual%20work%20shirt%2C%20warm%20friendly%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20photography%2C%20natural%20lighting%2C%20sharp%20detail&width=200&height=200&seq=7&orientation=squarish",
    available: true,
    vatNumber: "GB111222333",
    companyNumber: "11223344",
  },
  {
    id: "mc-8",
    companyName: "FreshCoat Decorators",
    trade: "Decorator",
    contactName: "Lisa Turner",
    email: "lisa@freshcoat.co.uk",
    phone: "0117 555 0810",
    rating: 4.7,
    totalJobs: 38,
    completedJobs: 36,
    responseTimeHours: 5.5,
    onTimeRate: 90,
    hourlyRate: 45,
    avgQuoteAmount: 850,
    status: "active",
    serviceAreas: ["Bristol", "Bath", "Gloucester"],
    insurance: [
      { type: "Public Liability", provider: "AXA Insurance", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£2,000,000" },
    ],
    certifications: [
      { name: "Painting & Decorating Association", issuer: "PDA", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "15 Jun 2026", rating: 5, text: "Beautiful job. The property looks brand new. Tenants delighted.", jobType: "Full Repaint" },
      { reviewer: "Sarah Collins", date: "01 Jun 2026", rating: 4, text: "Good quality work. Finished on time. Minor touch-up needed.", jobType: "Living Room" },
    ],
    recentJobs: [
      { title: "Full flat repaint", property: "Rose Court Flat 2A", amount: 1250, date: "15 Jun 2026", status: "Completed" },
      { title: "Living room decoration", property: "Riverside Court", amount: 680, date: "01 Jun 2026", status: "Completed" },
    ],
    bio: "Professional painting and decorating services. Interior and exterior work. Specialising in rental property makeovers between tenancies.",
    memberSince: "Apr 2023",
    paymentTerms: "14 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20female%20decorator%20headshot%20portrait%2C%20wearing%20paint-splattered%20overalls%20over%20a%20white%20top%2C%20warm%20friendly%20smile%2C%20clean%20studio%20background%2C%20professional%20photography%2C%20soft%20natural%20lighting&width=200&height=200&seq=8&orientation=squarish",
    available: true,
    vatNumber: "GB444555666",
    companyNumber: "44556677",
  },
  {
    id: "mc-9",
    companyName: "SparkleClean Services",
    trade: "Cleaner",
    contactName: "Angela Price",
    email: "hello@sparkleclean.co.uk",
    phone: "020 555 0910",
    rating: 4.4,
    totalJobs: 112,
    completedJobs: 105,
    responseTimeHours: 2.8,
    onTimeRate: 93,
    hourlyRate: 25,
    avgQuoteAmount: 180,
    status: "active",
    serviceAreas: ["London", "Surrey", "Kent"],
    insurance: [
      { type: "Public Liability", provider: "Hiscox", expiry: "01 Sep 2026", status: "Valid", coverAmount: "£1,000,000" },
    ],
    certifications: [],
    reviews: [
      { reviewer: "Sarah Collins", date: "18 Jun 2026", rating: 5, text: "End of tenancy clean was spotless. Deposit returned without any cleaning deductions.", jobType: "End of Tenancy Clean" },
      { reviewer: "James Hart", date: "05 Jun 2026", rating: 4, text: "Regular weekly clean. Reliable and thorough.", jobType: "Weekly Clean" },
      { reviewer: "Sarah Collins", date: "20 May 2026", rating: 4, text: "Good deep clean. Couple of areas could have been better.", jobType: "Deep Clean" },
    ],
    recentJobs: [
      { title: "End of tenancy clean", property: "Rose Court Flat 2A", amount: 220, date: "18 Jun 2026", status: "Completed" },
      { title: "Weekly communal clean", property: "Riverside Court", amount: 95, date: "05 Jun 2026", status: "Completed" },
    ],
    bio: "Residential and commercial cleaning specialists. End of tenancy cleans, deep cleans, and regular maintenance cleaning for rental properties.",
    memberSince: "Feb 2023",
    paymentTerms: "7 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20female%20cleaner%20headshot%20portrait%2C%20wearing%20a%20clean%20blue%20uniform%20polo%20shirt%2C%20bright%20friendly%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20photography%2C%20soft%20lighting%2C%20sharp%20focus&width=200&height=200&seq=9&orientation=squarish",
    available: true,
    vatNumber: "GB777888999",
    companyNumber: "77889900",
  },
  {
    id: "mc-10",
    companyName: "InventoryPro UK",
    trade: "Inventory Clerk",
    contactName: "Rachel Knight",
    email: "reports@inventorypro.co.uk",
    phone: "0161 555 1020",
    rating: 4.6,
    totalJobs: 156,
    completedJobs: 150,
    responseTimeHours: 4.5,
    onTimeRate: 95,
    hourlyRate: 35,
    avgQuoteAmount: 145,
    status: "active",
    serviceAreas: ["Manchester", "Liverpool", "Preston", "Warrington"],
    insurance: [
      { type: "Public Liability", provider: "Aviva", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£1,000,000" },
      { type: "Professional Indemnity", provider: "Aviva", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£500,000" },
    ],
    certifications: [
      { name: "AIIC Registered", issuer: "AIIC", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
      { name: "Propertymark Approved", issuer: "Propertymark", date: "01 Mar 2026", expiry: "28 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "20 Jun 2026", rating: 5, text: "Extremely thorough inventory report. 150 photos and detailed notes. Best we've used.", jobType: "Check-in Inventory" },
      { reviewer: "Sarah Collins", date: "10 Jun 2026", rating: 4, text: "Good inventory service. Report delivered within 48 hours.", jobType: "Check-out Inventory" },
      { reviewer: "James Hart", date: "28 May 2026", rating: 5, text: "Fair and detailed. Has helped us resolve multiple deposit disputes.", jobType: "Mid-term Inspection" },
    ],
    recentJobs: [
      { title: "Check-in inventory", property: "Rose Court Flat 2A", amount: 155, date: "20 Jun 2026", status: "Completed" },
      { title: "Check-out inventory", property: "Maple Gardens House", amount: 145, date: "10 Jun 2026", status: "Completed" },
    ],
    bio: "Professional inventory services for letting agents and landlords. Check-in, check-out, and mid-term reports with detailed photographic evidence.",
    memberSince: "Mar 2022",
    paymentTerms: "14 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20female%20inventory%20clerk%20headshot%20portrait%2C%20wearing%20smart%20casual%20blazer%2C%20confident%20smile%2C%20clean%20white%20studio%20background%2C%20professional%20corporate%20photography%2C%20soft%20lighting%2C%20sharp%20detail&width=200&height=200&seq=10&orientation=squarish",
    available: true,
    vatNumber: "GB999000111",
    companyNumber: "99001122",
  },
  {
    id: "mc-11",
    companyName: "EcoEPC Assessments",
    trade: "EPC Assessor",
    contactName: "Michael Grant",
    email: "info@ecoepc.co.uk",
    phone: "0121 555 1150",
    rating: 4.3,
    totalJobs: 98,
    completedJobs: 94,
    responseTimeHours: 6.5,
    onTimeRate: 88,
    hourlyRate: 50,
    avgQuoteAmount: 85,
    status: "active",
    serviceAreas: ["Birmingham", "Coventry", "Solihull", "Worcester"],
    insurance: [
      { type: "Public Liability", provider: "Zurich", expiry: "28 Feb 2027", status: "Valid", coverAmount: "£1,000,000" },
      { type: "Professional Indemnity", provider: "Zurich", expiry: "28 Feb 2027", status: "Valid", coverAmount: "£250,000" },
    ],
    certifications: [
      { name: "Accredited Energy Assessor", issuer: "Elmhurst Energy", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
    ],
    reviews: [
      { reviewer: "Sarah Collins", date: "15 Jun 2026", rating: 4, text: "Good service. Certificate delivered quickly. Competitive pricing.", jobType: "EPC Certificate" },
      { reviewer: "James Hart", date: "01 Jun 2026", rating: 4, text: "Reliable. Had the EPC done within a week of booking.", jobType: "EPC Renewal" },
    ],
    recentJobs: [
      { title: "EPC certificate", property: "Rose Court Flat 2A", amount: 85, date: "15 Jun 2026", status: "Completed" },
      { title: "EPC renewal", property: "Riverside Court", amount: 80, date: "01 Jun 2026", status: "Completed" },
    ],
    bio: "Domestic energy assessor providing EPC certificates across the Midlands. Fast turnaround, competitive pricing, fully accredited.",
    memberSince: "May 2023",
    paymentTerms: "7 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20EPC%20assessor%20headshot%20portrait%2C%20wearing%20smart%20casual%20shirt%2C%20friendly%20professional%20smile%2C%20clean%20white%20studio%20background%2C%20corporate%20photography%2C%20soft%20lighting&width=200&height=200&seq=11&orientation=squarish",
    available: true,
    vatNumber: "GB222333444",
    companyNumber: "22334455",
  },
  {
    id: "mc-12",
    companyName: "Certify Electrical Ltd",
    trade: "EICR Contractor",
    contactName: "Alan Fisher",
    email: "certify@electricalcert.co.uk",
    phone: "0113 555 1250",
    rating: 4.5,
    totalJobs: 64,
    completedJobs: 60,
    responseTimeHours: 5.2,
    onTimeRate: 85,
    hourlyRate: 70,
    avgQuoteAmount: 195,
    status: "active",
    serviceAreas: ["Leeds", "Sheffield", "Doncaster", "Wakefield"],
    insurance: [
      { type: "Public Liability", provider: "AXA Insurance", expiry: "30 Sep 2026", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Professional Indemnity", provider: "AXA Insurance", expiry: "30 Sep 2026", status: "Valid", coverAmount: "£1,000,000" },
    ],
    certifications: [
      { name: "NICEIC Approved Contractor", issuer: "NICEIC", date: "15 Jan 2026", expiry: "14 Jan 2027", status: "Valid" },
      { name: "NAPIT Registered", issuer: "NAPIT", date: "01 Mar 2026", expiry: "28 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "12 Jun 2026", rating: 5, text: "Thorough EICR inspection. Clear report with all issues prioritised.", jobType: "EICR Inspection" },
      { reviewer: "Sarah Collins", date: "28 May 2026", rating: 4, text: "Good work. All remedial works completed within quote.", jobType: "Remedial Works" },
    ],
    recentJobs: [
      { title: "EICR inspection", property: "Riverside Court", amount: 195, date: "12 Jun 2026", status: "Completed" },
      { title: "Remedial electrical works", property: "Maple Gardens House", amount: 450, date: "28 May 2026", status: "Completed" },
    ],
    bio: "Specialist EICR testing and inspection. Full electrical installation condition reports with detailed findings and remedial recommendations.",
    memberSince: "Jun 2023",
    paymentTerms: "14 days",
    emergencyCallout: true,
    emergencyFee: "£130 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20electrical%20contractor%20headshot%20portrait%2C%20wearing%20navy%20work%20polo%20shirt%2C%20friendly%20smile%2C%20clean%20white%20studio%20background%2C%20corporate%20photography%2C%20soft%20diffused%20lighting&width=200&height=200&seq=12&orientation=squarish",
    available: true,
    vatNumber: "GB555666777",
    companyNumber: "55667788",
  },
  {
    id: "mc-13",
    companyName: "Guardian Fire Safety",
    trade: "Fire Safety Contractor",
    contactName: "Chris Dalton",
    email: "info@guardianfire.co.uk",
    phone: "0161 555 1350",
    rating: 4.8,
    totalJobs: 72,
    completedJobs: 68,
    responseTimeHours: 3.5,
    onTimeRate: 92,
    hourlyRate: 65,
    avgQuoteAmount: 350,
    status: "active",
    serviceAreas: ["Manchester", "Liverpool", "Bolton", "Warrington"],
    insurance: [
      { type: "Public Liability", provider: "Allianz", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Employers Liability", provider: "Allianz", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£10,000,000" },
    ],
    certifications: [
      { name: "BAFE Registered", issuer: "BAFE", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
      { name: "Fire Industry Association", issuer: "FIA", date: "01 Mar 2026", expiry: "28 Feb 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "Sarah Collins", date: "18 Jun 2026", rating: 5, text: "Comprehensive fire risk assessment. Very thorough. Report was excellent.", jobType: "Fire Risk Assessment" },
      { reviewer: "James Hart", date: "05 Jun 2026", rating: 5, text: "Installed fire doors across three properties. Clean work, on time.", jobType: "Fire Door Installation" },
      { reviewer: "Sarah Collins", date: "20 May 2026", rating: 4, text: "Good service. Alarm system tested and certified.", jobType: "Alarm Testing" },
    ],
    recentJobs: [
      { title: "Fire risk assessment", property: "Rose Court Flats", amount: 380, date: "18 Jun 2026", status: "Completed" },
      { title: "Fire door installation", property: "Maple Gardens House", amount: 1250, date: "05 Jun 2026", status: "Completed" },
    ],
    bio: "Fire safety specialists for residential rental properties. Fire risk assessments, alarm installation and testing, fire doors, and emergency lighting.",
    memberSince: "Jan 2023",
    paymentTerms: "14 days",
    emergencyCallout: true,
    emergencyFee: "£140 + VAT",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20fire%20safety%20contractor%20headshot%20portrait%2C%20wearing%20branded%20navy%20polo%20shirt%20with%20fire%20safety%20logo%2C%20confident%20friendly%20smile%2C%20clean%20white%20studio%20background%2C%20corporate%20photography%2C%20soft%20lighting&width=200&height=200&seq=13&orientation=squarish",
    available: true,
    vatNumber: "GB888999000",
    companyNumber: "88990011",
  },
  {
    id: "mc-14",
    companyName: "DryHome Solutions",
    trade: "Damp & Mould Specialist",
    contactName: "Dr. Emma Wilson",
    email: "help@dryhome.co.uk",
    phone: "020 555 1450",
    rating: 4.6,
    totalJobs: 54,
    completedJobs: 50,
    responseTimeHours: 5.8,
    onTimeRate: 87,
    hourlyRate: 65,
    avgQuoteAmount: 680,
    status: "active",
    serviceAreas: ["London", "Essex", "Hertfordshire", "Surrey"],
    insurance: [
      { type: "Public Liability", provider: "AXA Insurance", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£5,000,000" },
      { type: "Professional Indemnity", provider: "AXA Insurance", expiry: "30 Jun 2027", status: "Valid", coverAmount: "£1,000,000" },
    ],
    certifications: [
      { name: "PCA Registered", issuer: "Property Care Association", date: "01 Jan 2026", expiry: "31 Dec 2026", status: "Valid" },
      { name: "CSRT Qualified", issuer: "PCA", date: "01 Feb 2026", expiry: "31 Jan 2027", status: "Valid" },
    ],
    reviews: [
      { reviewer: "James Hart", date: "20 Jun 2026", rating: 5, text: "Identified the root cause of damp that three others missed. Problem solved permanently.", jobType: "Damp Survey" },
      { reviewer: "Sarah Collins", date: "08 Jun 2026", rating: 4, text: "Good mould treatment. Follow-up visit confirmed it hasn't returned.", jobType: "Mould Treatment" },
      { reviewer: "James Hart", date: "25 May 2026", rating: 5, text: "Professional damp proofing work. Tenants report the property is now warm and dry.", jobType: "Damp Proofing" },
    ],
    recentJobs: [
      { title: "Damp survey and report", property: "Riverside Court", amount: 350, date: "20 Jun 2026", status: "Completed" },
      { title: "Mould treatment", property: "Rose Court Flat 2A", amount: 480, date: "08 Jun 2026", status: "Completed" },
    ],
    bio: "Specialist damp and mould surveyors and contractors. Identifying root causes, providing treatment solutions, and preventing recurrence in rental properties.",
    memberSince: "Sep 2023",
    paymentTerms: "14 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20female%20damp%20specialist%20headshot%20portrait%2C%20wearing%20professional%20blouse%2C%20warm%20confident%20smile%2C%20clean%20white%20studio%20background%2C%20corporate%20photography%2C%20soft%20natural%20lighting&width=200&height=200&seq=14&orientation=squarish",
    available: true,
    vatNumber: "GB333444555",
    companyNumber: "33445566",
  },
  {
    id: "mc-15",
    companyName: "FastFix Property Services",
    trade: "Handyman",
    contactName: "Mike Davies",
    email: "contractor@example.com",
    phone: "07700 900002",
    rating: 4.5,
    totalJobs: 34,
    completedJobs: 34,
    responseTimeHours: 4.0,
    onTimeRate: 90,
    hourlyRate: 55,
    avgQuoteAmount: 140,
    status: "active",
    serviceAreas: ["London", "Bristol"],
    insurance: [
      { type: "Public Liability", provider: "Direct Line", expiry: "31 Dec 2026", status: "Valid", coverAmount: "£2,000,000" },
    ],
    certifications: [],
    reviews: [
      { reviewer: "James Hart", date: "10 May 2026", rating: 5, text: "Reliable and quick. Gets the job done with no fuss.", jobType: "General Repairs" },
    ],
    recentJobs: [
      { title: "General maintenance", property: "Maple Gardens House", amount: 195, date: "10 May 2026", status: "Completed" },
    ],
    bio: "Reliable property maintenance and handyman services. Quick turnaround on all types of repairs. Over 30 years combined experience.",
    memberSince: "Jun 2024",
    paymentTerms: "7 days",
    emergencyCallout: false,
    emergencyFee: "",
    avatar: "https://readdy.ai/api/search-image?query=Professional%20male%20handyman%20headshot%20portrait%2C%20wearing%20casual%20work%20polo%20shirt%2C%20warm%20friendly%20smile%2C%20clean%20studio%20background%2C%20professional%20photography%2C%20natural%20lighting%2C%20sharp%20detail&width=200&height=200&seq=15&orientation=squarish",
    available: true,
    vatNumber: "GB123123123",
    companyNumber: "12312312",
  },
];

export const assignedContractors = [
  { contractorId: "mc-1", contractorName: "GreenPlumb Ltd", trade: "Plumber", property: "Rose Court Flat 2A", jobTitle: "Boiler pressure loss", assignedDate: "25 May 2026", status: "Quoted", quoteAmount: 336 },
  { contractorId: "mc-2", contractorName: "Bright Spark Electrical", trade: "Electrician", property: "Rose Court Flat 2A", jobTitle: "Bathroom extractor fan", assignedDate: "16 May 2026", status: "Completed", quoteAmount: 174 },
  { contractorId: "mc-14", contractorName: "DryHome Solutions", trade: "Damp & Mould Specialist", property: "Rose Court Flat 2A", jobTitle: "Mould treatment", assignedDate: "08 Jun 2026", status: "Completed", quoteAmount: 480 },
  { contractorId: "mc-9", contractorName: "SparkleClean Services", trade: "Cleaner", property: "Rose Court Flat 2A", jobTitle: "End of tenancy clean", assignedDate: "18 Jun 2026", status: "Completed", quoteAmount: 220 },
];

export const pendingQuotes = [
  { id: "pq-1", contractorId: "mc-3", contractorName: "GasSafe Pro Solutions", trade: "Gas Engineer", property: "Rose Court Flat 2A", jobTitle: "Annual gas safety check", amount: 95, requestedDate: "22 Jun 2026", status: "Awaiting Quote" },
  { id: "pq-2", contractorId: "mc-13", contractorName: "Guardian Fire Safety", trade: "Fire Safety Contractor", property: "Riverside Court", jobTitle: "Fire risk assessment", amount: undefined, requestedDate: "21 Jun 2026", status: "Awaiting Quote" },
  { id: "pq-3", contractorId: "mc-1", contractorName: "GreenPlumb Ltd", trade: "Plumber", property: "Rose Court Flat 2A", jobTitle: "Boiler pressure loss", amount: 336, requestedDate: "26 May 2026", status: "Pending Approval" },
  { id: "pq-4", contractorId: "mc-5", contractorName: "Summit Roofing Ltd", trade: "Roofer", property: "Maple Gardens House", jobTitle: "Flat roof inspection", amount: 350, requestedDate: "18 Jun 2026", status: "Submitted" },
  { id: "pq-5", contractorId: "mc-7", contractorName: "FixIt Handyman Services", trade: "Handyman", property: "Riverside Court", jobTitle: "Door handle replacement", amount: 65, requestedDate: "15 Jun 2026", status: "Approved" },
];

export const tradeIconMap: Record<string, string> = {
  "Electrician": "ri-flashlight-line",
  "Plumber": "ri-drop-line",
  "Gas Engineer": "ri-fire-line",
  "Locksmith": "ri-key-2-line",
  "Roofer": "ri-home-3-line",
  "Builder": "ri-hammer-line",
  "Handyman": "ri-tools-line",
  "Decorator": "ri-paint-brush-line",
  "Cleaner": "ri-shining-line",
  "Inventory Clerk": "ri-clipboard-line",
  "EPC Assessor": "ri-file-chart-line",
  "EICR Contractor": "ri-shield-flash-line",
  "Fire Safety Contractor": "ri-alarm-warning-line",
  "Damp & Mould Specialist": "ri-contrast-drop-line",
};

export const tradeColorMap: Record<string, string> = {
  "Electrician": "#F59E0B",
  "Plumber": "#3B82F6",
  "Gas Engineer": "#EF4444",
  "Locksmith": "#6B7280",
  "Roofer": "#D97706",
  "Builder": "#F97316",
  "Handyman": "#14B8A6",
  "Decorator": "#8B5CF6",
  "Cleaner": "#22C55E",
  "Inventory Clerk": "#6366F1",
  "EPC Assessor": "#0EA5E9",
  "EICR Contractor": "#7C3AED",
  "Fire Safety Contractor": "#DC2626",
  "Damp & Mould Specialist": "#0891B2",
};