"use client";

import PropertyDetailView, { PropertyDetailData } from "@/components/property/PropertyDetailView";

const nationLabels: Record<string, string> = {
  england: "England", wales: "Wales", scotland: "Scotland", northern_ireland: "Northern Ireland",
};

const propertiesMock: PropertyDetailData[] = [
  { id: "1", name: "12 Rose Avenue", address: "12 Rose Avenue", city: "Manchester", postcode: "M20 3NB", type: "Flat", bedrooms: 2, bathrooms: 1, nation: "england", nationLabel: "England", status: "Occupied", rentAmount: 950, depositAmount: 1096, landlordName: "James Richardson", landlordEmail: "james@example.com", tenantName: "John Miller", tenantEmail: "john@email.com", propertyManager: "Sarah Jones", tenancyStart: "2025-08-15", tenancyEnd: "2026-08-14", epcRating: "C", gasExpiry: "2026-10-12", eicrExpiry: "2027-03-05", complianceStatus: "Valid", maintenanceOpen: 2, ownerPortal: "active", tenantPortal: "active", isHmo: false, isFurnished: true, dateAdded: "2024-06-10", image: "https://readdy.ai/api/search-image?query=Modern%20UK%20residential%20flat%20exterior%20with%20brick%20facade%2C%20bay%20windows%2C%20well-maintained%20front%20garden%2C%20professional%20real%20estate%20photography%20style%2C%20neutral%20warm%20tones%2C%20clean%20background%2C%20suburban%20setting&width=800&height=500&seq=prop-det-1&orientation=landscape", isLiveData: false },
  { id: "2", name: "45 Oak Court", address: "45 Oak Court", city: "Birmingham", postcode: "B15 2PL", type: "Semi-Detached", bedrooms: 3, bathrooms: 2, nation: "england", nationLabel: "England", status: "Occupied", rentAmount: 1250, depositAmount: 1442, landlordName: "Sarah Chen", landlordEmail: "sarah.chen@email.com", tenantName: "Emily Watson", tenantEmail: "emily.w@email.com", propertyManager: "Mark Wilson", tenancyStart: "2025-11-01", tenancyEnd: "2026-10-31", epcRating: "B", gasExpiry: "2026-05-20", eicrExpiry: "2026-11-15", complianceStatus: "Expiring Soon", maintenanceOpen: 0, ownerPortal: "active", tenantPortal: "invited", isHmo: false, isFurnished: false, dateAdded: "2024-09-22", image: "https://readdy.ai/api/search-image?query=Semi-detached%20UK%20house%20with%20red%20brick%20exterior%2C%20large%20bay%20windows%2C%20neat%20front%20garden%20with%20hedge%2C%20professional%20property%20photography%2C%20natural%20daylight%2C%20warm%20tones%2C%20residential%20street%20setting&width=800&height=500&seq=prop-det-2&orientation=landscape", isLiveData: false },
  { id: "3", name: "78 Park View", address: "78 Park View", city: "Leeds", postcode: "LS6 1AH", type: "Terraced", bedrooms: 4, bathrooms: 2, nation: "england", nationLabel: "England", status: "Occupied", rentAmount: 1600, depositAmount: 1846, landlordName: "David Olu", landlordEmail: "david.olu@email.com", tenantName: "Rachel Green", tenantEmail: "rachel.g@email.com", propertyManager: null, tenancyStart: "2025-06-01", tenancyEnd: "2026-05-31", epcRating: "D", gasExpiry: "2025-08-15", eicrExpiry: "2027-01-20", complianceStatus: "Overdue", maintenanceOpen: 3, ownerPortal: "invited", tenantPortal: "active", isHmo: true, isFurnished: true, dateAdded: "2024-03-15", image: "https://readdy.ai/api/search-image?query=Terraced%20UK%20townhouse%20with%20red%20brick%20front%2C%20white%20window%20frames%2C%20traditional%20Victorian%20style%2C%20clean%20street%20view%2C%20professional%20real%20estate%20photography%2C%20warm%20afternoon%20light%2C%20urban%20residential%20area&width=800&height=500&seq=prop-det-3&orientation=landscape", isLiveData: false },
  { id: "4", name: "3 The Willows", address: "3 The Willows", city: "Edinburgh", postcode: "EH12 5PR", type: "Detached", bedrooms: 5, bathrooms: 3, nation: "scotland", nationLabel: "Scotland", status: "Vacant", rentAmount: 2200, depositAmount: 2538, landlordName: "Fiona MacLeod", landlordEmail: "fiona.m@email.com", tenantName: null, tenantEmail: null, propertyManager: "Alistair Brown", tenancyStart: null, tenancyEnd: null, epcRating: "A", gasExpiry: "2027-02-28", eicrExpiry: "2028-06-10", complianceStatus: "Valid", maintenanceOpen: 1, ownerPortal: "not-invited", tenantPortal: "not-invited", isHmo: false, isFurnished: false, dateAdded: "2024-11-05", image: "https://readdy.ai/api/search-image?query=Large%20detached%20Scottish%20stone%20house%20with%20slate%20roof%2C%20expansive%20front%20garden%2C%20gravel%20driveway%2C%20professional%20real%20estate%20photography%2C%20natural%20light%2C%20green%20surroundings%2C%20upscale%20residential%20area&width=800&height=500&seq=prop-det-4&orientation=landscape", isLiveData: false },
  { id: "5", name: "22 Riverside Court", address: "22 Riverside Court", city: "Cardiff", postcode: "CF10 5BT", type: "Apartment", bedrooms: 1, bathrooms: 1, nation: "wales", nationLabel: "Wales", status: "Occupied", rentAmount: 750, depositAmount: 865, landlordName: "Gareth Williams", landlordEmail: "gareth.w@email.com", tenantName: "Tom Baker", tenantEmail: "tom.b@email.com", propertyManager: null, tenancyStart: "2026-01-15", tenancyEnd: "2027-01-14", epcRating: "C", gasExpiry: "2026-09-30", eicrExpiry: "2027-07-22", complianceStatus: "Valid", maintenanceOpen: 0, ownerPortal: "active", tenantPortal: "active", isHmo: false, isFurnished: true, dateAdded: "2025-02-18", image: "https://readdy.ai/api/search-image?query=Modern%20waterfront%20apartment%20building%20UK%2C%20glass%20balconies%2C%20riverside%20location%2C%20contemporary%20architecture%2C%20professional%20property%20photography%2C%20blue%20sky%20reflected%20on%20water%2C%20urban%20setting&width=800&height=500&seq=prop-det-5&orientation=landscape", isLiveData: false },
  { id: "6", name: "9 Hillcrest Road", address: "9 Hillcrest Road", city: "Bristol", postcode: "BS6 5NL", type: "Semi-Detached", bedrooms: 3, bathrooms: 1, nation: "england", nationLabel: "England", status: "Maintenance", rentAmount: 1100, depositAmount: 1269, landlordName: "Amir Khan", landlordEmail: "amir.k@email.com", tenantName: "Lisa Brown", tenantEmail: "lisa.b@email.com", propertyManager: "Tom Harris", tenancyStart: "2024-06-01", tenancyEnd: "2025-05-31", epcRating: "E", gasExpiry: "2024-12-01", eicrExpiry: "2025-04-10", complianceStatus: "Overdue", maintenanceOpen: 4, ownerPortal: "active", tenantPortal: "active", isHmo: false, isFurnished: true, dateAdded: "2024-01-20", image: "https://readdy.ai/api/search-image?query=UK%20semi-detached%20house%20on%20a%20hill%20with%20stone%20facade%2C%20mature%20trees%20in%20front%20garden%2C%20classic%20British%20suburban%20architecture%2C%20professional%20real%20estate%20photography%2C%20soft%20morning%20light%2C%20leafy%20neighbourhood&width=800&height=500&seq=prop-det-6&orientation=landscape", isLiveData: false },
  { id: "7", name: "15 Meadow Lane", address: "15 Meadow Lane", city: "Nottingham", postcode: "NG7 2RD", type: "Flat", bedrooms: 2, bathrooms: 1, nation: "england", nationLabel: "England", status: "Available", rentAmount: 820, depositAmount: 946, landlordName: null, landlordEmail: null, tenantName: null, tenantEmail: null, propertyManager: null, tenancyStart: null, tenancyEnd: null, epcRating: "C", gasExpiry: null, eicrExpiry: null, complianceStatus: "Missing", maintenanceOpen: 0, ownerPortal: "not-invited", tenantPortal: "not-invited", isHmo: false, isFurnished: false, dateAdded: "2025-01-10", image: "https://readdy.ai/api/search-image?query=Modern%20UK%20flat%20exterior%20with%20brick%20facade%2C%20double%20glazed%20windows%2C%20well-maintained%20communal%20entrance%2C%20professional%20real%20estate%20photography%2C%20natural%20daylight%2C%20clean%20suburban%20setting&width=800&height=500&seq=prop-det-7&orientation=landscape", isLiveData: false },
  { id: "8", name: "33 Harbour View", address: "33 Harbour View", city: "Southampton", postcode: "SO14 3BN", type: "Apartment", bedrooms: 2, bathrooms: 1, nation: "england", nationLabel: "England", status: "Occupied", rentAmount: 980, depositAmount: 1130, landlordName: "Kate Murphy", landlordEmail: "kate.murphy@email.com", tenantName: null, tenantEmail: null, propertyManager: null, tenancyStart: "2025-10-15", tenancyEnd: "2026-10-14", epcRating: "B", gasExpiry: "2026-08-20", eicrExpiry: "2027-02-10", complianceStatus: "Valid", maintenanceOpen: 1, ownerPortal: "active", tenantPortal: "not-invited", isHmo: false, isFurnished: true, dateAdded: "2025-03-05", image: "https://readdy.ai/api/search-image?query=UK%20harbour%20view%20apartment%20building%20with%20modern%20architecture%2C%20glass%20balconies%20facing%20water%2C%20blue%20sky%2C%20professional%20real%20estate%20photography%2C%20coastal%20urban%20setting&width=800&height=500&seq=prop-det-8&orientation=landscape", isLiveData: false },
  { id: "9", name: "55 Green Lane", address: "55 Green Lane", city: "Sheffield", postcode: "S10 2TH", type: "Terraced", bedrooms: 3, bathrooms: 1, nation: "england", nationLabel: "England", status: "Vacant", rentAmount: 900, depositAmount: 1038, landlordName: "Robert Taylor", landlordEmail: "robert.t@email.com", tenantName: null, tenantEmail: null, propertyManager: null, tenancyStart: null, tenancyEnd: null, epcRating: "D", gasExpiry: "2026-03-15", eicrExpiry: "2026-09-30", complianceStatus: "Expiring Soon", maintenanceOpen: 0, ownerPortal: "invited", tenantPortal: "not-invited", isHmo: false, isFurnished: false, dateAdded: "2024-08-12", image: "https://readdy.ai/api/search-image?query=Terraced%20UK%20house%20with%20red%20brick%20exterior%20and%20green%20front%20door%2C%20well-kept%20front%20garden%20with%20fence%2C%20professional%20real%20estate%20photography%2C%20natural%20daylight%2C%20quiet%20residential%20street&width=800&height=500&seq=prop-det-9&orientation=landscape", isLiveData: false },
  { id: "10", name: "72 Castle Gate", address: "72 Castle Gate", city: "Newcastle", postcode: "NE1 4SN", type: "Flat", bedrooms: 1, bathrooms: 1, nation: "england", nationLabel: "England", status: "Occupied", rentAmount: 650, depositAmount: 750, landlordName: null, landlordEmail: null, tenantName: "Mike Davis", tenantEmail: "mike.d@email.com", propertyManager: null, tenancyStart: "2025-07-01", tenancyEnd: "2026-06-30", epcRating: "C", gasExpiry: "2026-11-05", eicrExpiry: "2027-04-18", complianceStatus: "Valid", maintenanceOpen: 0, ownerPortal: "not-invited", tenantPortal: "active", isHmo: false, isFurnished: true, dateAdded: "2025-05-20", image: "https://readdy.ai/api/search-image?query=Newcastle%20city%20centre%20flat%2C%20modern%20exterior%2C%20large%20windows%2C%20urban%20setting%2C%20professional%20property%20photography%2C%20neutral%20tones&width=800&height=500&seq=prop-det-10&orientation=landscape", isLiveData: false },
];

export default function PropertyDetail({ propertyId }: { propertyId: string }) {
  const property = propertiesMock.find((p) => p.id === propertyId) || null;
  return <PropertyDetailView property={property} loading={false} notFound={!property} />;
}