export interface TenancyRecord {
  id: string
  ref: string
  propertyId: string
  propertyName: string
  propertyAddress: string
  tenantId: string
  tenantName: string
  tenantEmail: string
  tenantPhone: string
  ownerId: string
  ownerName: string
  ownerEmail: string
  startDate: string
  endDate: string
  periodic: boolean
  rent: number
  deposit: number
  depositScheme: string
  status: "draft" | "active" | "ending" | "ended" | "archived"
  ownerPortalStatus: string
  tenantPortalStatus: string
  rentDueDay: number
  noticeRequired: string
  propertyType: string
  bedrooms: number
  lastInspection: string
  nextInspection: string
}

export const tenancies: TenancyRecord[] = [
  {
    id: "tncy-001",
    ref: "TNCY-2024-001",
    propertyId: "prop-001",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    tenantId: "tnt-001",
    tenantName: "John Miller",
    tenantEmail: "john.miller@email.com",
    tenantPhone: "+44 7700 900456",
    ownerId: "own-001",
    ownerName: "James Richardson",
    ownerEmail: "james.richardson@email.com",
    startDate: "15 Sep 2024",
    endDate: "14 Sep 2026",
    periodic: false,
    rent: 1850,
    deposit: 1850,
    depositScheme: "MyDeposits",
    status: "active",
    ownerPortalStatus: "active",
    tenantPortalStatus: "active",
    rentDueDay: 1,
    noticeRequired: "2 months",
    propertyType: "Flat",
    bedrooms: 2,
    lastInspection: "10 Feb 2026",
    nextInspection: "20 Jun 2026",
  },
  {
    id: "tncy-002",
    ref: "TNCY-2025-002",
    propertyId: "prop-003",
    propertyName: "Oak Court",
    propertyAddress: "Oak Court, 5 Oak Lane, Manchester M20 1AB",
    tenantId: "tnt-002",
    tenantName: "Emily Watson",
    tenantEmail: "emily.watson@email.com",
    tenantPhone: "+44 7700 900788",
    ownerId: "own-002",
    ownerName: "Sarah Chen",
    ownerEmail: "sarah.chen@email.com",
    startDate: "01 Sep 2025",
    endDate: "31 Aug 2026",
    periodic: false,
    rent: 1250,
    deposit: 1250,
    depositScheme: "TDS",
    status: "active",
    ownerPortalStatus: "active",
    tenantPortalStatus: "active",
    rentDueDay: 1,
    noticeRequired: "1 month",
    propertyType: "Flat",
    bedrooms: 1,
    lastInspection: "15 Mar 2026",
    nextInspection: "15 Sep 2026",
  },
  {
    id: "tncy-003",
    ref: "TNCY-2026-003",
    propertyId: "prop-004",
    propertyName: "Park View House",
    propertyAddress: "17 Park View, Birmingham B15 2TT",
    tenantId: "tnt-003",
    tenantName: "Rachel Green",
    tenantEmail: "rachel.green@email.com",
    tenantPhone: "+44 7700 900321",
    ownerId: "own-003",
    ownerName: "David Olu",
    ownerEmail: "david.olu@email.com",
    startDate: "10 Jan 2026",
    endDate: "09 Jan 2027",
    periodic: false,
    rent: 1600,
    deposit: 2400,
    depositScheme: "MyDeposits",
    status: "active",
    ownerPortalStatus: "invited",
    tenantPortalStatus: "active",
    rentDueDay: 10,
    noticeRequired: "2 months",
    propertyType: "House",
    bedrooms: 3,
    lastInspection: "10 Jan 2026",
    nextInspection: "10 Jul 2026",
  },
  {
    id: "tncy-004",
    ref: "TNCY-2025-004",
    propertyId: "prop-002",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    tenantId: "tnt-004",
    tenantName: "Tom Harris",
    tenantEmail: "tom.harris@email.com",
    tenantPhone: "+44 7700 900555",
    ownerId: "own-001",
    ownerName: "James Richardson",
    ownerEmail: "james.richardson@email.com",
    startDate: "05 Aug 2025",
    endDate: "04 Aug 2027",
    periodic: false,
    rent: 1950,
    deposit: 1950,
    depositScheme: "TDS",
    status: "active",
    ownerPortalStatus: "active",
    tenantPortalStatus: "active",
    rentDueDay: 5,
    noticeRequired: "2 months",
    propertyType: "Flat",
    bedrooms: 2,
    lastInspection: "15 Jan 2026",
    nextInspection: "15 Aug 2026",
  },
  {
    id: "tncy-005",
    ref: "TNCY-2026-005",
    propertyId: "prop-005",
    propertyName: "The Willows",
    propertyAddress: "22 The Willows, Edinburgh EH4 3BN",
    tenantId: "tnt-005",
    tenantName: "Amir Khan",
    tenantEmail: "amir.khan@email.com",
    tenantPhone: "+44 7700 900222",
    ownerId: "own-004",
    ownerName: "Fiona MacLeod",
    ownerEmail: "fiona.macleod@email.com",
    startDate: "08 Mar 2026",
    endDate: "07 Mar 2027",
    periodic: false,
    rent: 2200,
    deposit: 2200,
    depositScheme: "SafeDeposits Scotland",
    status: "active",
    ownerPortalStatus: "not_invited",
    tenantPortalStatus: "invited",
    rentDueDay: 8,
    noticeRequired: "1 month",
    propertyType: "Semi-Detached",
    bedrooms: 4,
    lastInspection: "08 Mar 2026",
    nextInspection: "08 Sep 2026",
  },
  {
    id: "tncy-006",
    ref: "TNCY-2024-006",
    propertyId: "prop-006",
    propertyName: "12 Derby Road",
    propertyAddress: "12 Derby Road, Manchester M14 5LL",
    tenantId: "tnt-006",
    tenantName: "Sophie Laurent",
    tenantEmail: "sophie.laurent@email.com",
    tenantPhone: "+44 7700 900333",
    ownerId: "own-005",
    ownerName: "Michael Okonkwo",
    ownerEmail: "michael.okonkwo@email.com",
    startDate: "15 Mar 2024",
    endDate: "14 Mar 2027",
    periodic: false,
    rent: 1100,
    deposit: 1100,
    depositScheme: "MyDeposits",
    status: "active",
    ownerPortalStatus: "active",
    tenantPortalStatus: "active",
    rentDueDay: 15,
    noticeRequired: "2 months",
    propertyType: "Terraced",
    bedrooms: 3,
    lastInspection: "20 Apr 2026",
    nextInspection: "20 Oct 2026",
  },
  {
    id: "tncy-007",
    ref: "TNCY-2024-007",
    propertyId: "prop-007",
    propertyName: "Flat 3 Ash House",
    propertyAddress: "Ash House, 90 Oxford Road, Manchester M13 9PG",
    tenantId: "tnt-008",
    tenantName: "Daniel Craig",
    tenantEmail: "daniel.craig@email.com",
    tenantPhone: "+44 7700 900888",
    ownerId: "own-005",
    ownerName: "Michael Okonkwo",
    ownerEmail: "michael.okonkwo@email.com",
    startDate: "01 Jul 2026",
    endDate: "30 Jun 2027",
    periodic: false,
    rent: 950,
    deposit: 950,
    depositScheme: "MyDeposits",
    status: "draft",
    ownerPortalStatus: "active",
    tenantPortalStatus: "not_invited",
    rentDueDay: 1,
    noticeRequired: "1 month",
    propertyType: "Flat",
    bedrooms: 1,
    lastInspection: "-",
    nextInspection: "TBC",
  },
  {
    id: "tncy-008",
    ref: "TNCY-2023-008",
    propertyId: "prop-009",
    propertyName: "Flat 1A Belgrave Road",
    propertyAddress: "1A Belgrave Road, Leicester LE4 5PH",
    tenantId: "tnt-007",
    tenantName: "Oliver Bennett",
    tenantEmail: "oliver.bennett@email.com",
    tenantPhone: "+44 7700 900444",
    ownerId: "own-006",
    ownerName: "Priya Patel",
    ownerEmail: "priya.patel@email.com",
    startDate: "12 Mar 2024",
    endDate: "11 Mar 2026",
    periodic: false,
    rent: 875,
    deposit: 875,
    depositScheme: "TDS",
    status: "ended",
    ownerPortalStatus: "disabled",
    tenantPortalStatus: "disabled",
    rentDueDay: 12,
    noticeRequired: "1 month",
    propertyType: "Flat",
    bedrooms: 2,
    lastInspection: "10 Jan 2026",
    nextInspection: "-",
  },
  {
    id: "tncy-009",
    ref: "TNCY-2023-009",
    propertyId: "prop-008",
    propertyName: "34 Moss Lane",
    propertyAddress: "34 Moss Lane, Manchester M16 7AE",
    tenantId: "",
    tenantName: "Vacant",
    tenantEmail: "",
    tenantPhone: "",
    ownerId: "own-005",
    ownerName: "Michael Okonkwo",
    ownerEmail: "michael.okonkwo@email.com",
    startDate: "01 May 2024",
    endDate: "30 Apr 2026",
    periodic: true,
    rent: 1350,
    deposit: 1350,
    depositScheme: "MyDeposits",
    status: "ending",
    ownerPortalStatus: "active",
    tenantPortalStatus: "disabled",
    rentDueDay: 1,
    noticeRequired: "1 month",
    propertyType: "Semi-Detached",
    bedrooms: 3,
    lastInspection: "05 Jan 2026",
    nextInspection: "-",
  },
  {
    id: "tncy-010",
    ref: "TNCY-2022-010",
    propertyId: "prop-010",
    propertyName: "27 Elm Grove",
    propertyAddress: "27 Elm Grove, Brighton BN2 3ET",
    tenantId: "",
    tenantName: "Student Group (3)",
    tenantEmail: "lead@brighton-uni.ac.uk",
    tenantPhone: "+44 7700 900777",
    ownerId: "own-007",
    ownerName: "Thomas Wright",
    ownerEmail: "thomas.wright@email.com",
    startDate: "01 Sep 2022",
    endDate: "31 Aug 2025",
    periodic: false,
    rent: 2400,
    deposit: 3600,
    depositScheme: "MyDeposits",
    status: "archived",
    ownerPortalStatus: "active",
    tenantPortalStatus: "disabled",
    rentDueDay: 1,
    noticeRequired: "2 months",
    propertyType: "Terraced",
    bedrooms: 5,
    lastInspection: "15 Jul 2025",
    nextInspection: "-",
  },
]

export const tenancyStatusBadge: Record<string, string> = {
  draft: "bg-[#94A3B8]/10 text-[#94A3B8]",
  active: "bg-[#10B981]/10 text-[#10B981]",
  ending: "bg-[#F59E0B]/10 text-[#F59E0B]",
  ended: "bg-[#8B5CF6]/10 text-[#8B5CF6]",
  archived: "bg-[#64748B]/10 text-[#64748B]",
}

export const tenancyStatusLabel: Record<string, string> = {
  draft: "Draft",
  active: "Active",
  ending: "Ending",
  ended: "Ended",
  archived: "Archived",
}

export const portalStatusBadge: Record<string, string> = {
  not_invited: "bg-[#94A3B8]/10 text-[#94A3B8]",
  invited: "bg-[#3B82F6]/10 text-[#3B82F6]",
  active: "bg-[#10B981]/10 text-[#10B981]",
  disabled: "bg-[#EF4444]/10 text-[#EF4444]",
}

export const portalStatusLabel: Record<string, string> = {
  not_invited: "Not Invited",
  invited: "Invited",
  active: "Active",
  disabled: "Disabled",
}