export interface TenantRecord {
  id: string
  fullName: string
  email: string
  phone: string
  currentPropertyId?: string
  currentPropertyName?: string
  currentPropertyAddress?: string
  tenancyId?: string
  tenancyRef?: string
  tenancyStatus?: string
  emergencyContactName?: string
  emergencyContactPhone?: string
  notes?: string
  portalStatus: "not_invited" | "invited" | "active" | "disabled"
  portalToken?: string
  inviteDate?: string
  lastLogin?: string
  dateAdded: string
}

export const tenants: TenantRecord[] = [
  {
    id: "tnt-001",
    fullName: "John Miller",
    email: "john.miller@email.com",
    phone: "+44 7700 900456",
    currentPropertyId: "prop-001",
    currentPropertyName: "Rose Court Flat 2A",
    currentPropertyAddress: "12 Rose Avenue, London E1 6AN",
    tenancyId: "tncy-001",
    tenancyRef: "TNCY-2024-001",
    tenancyStatus: "Active",
    emergencyContactName: "Jane Miller",
    emergencyContactPhone: "+44 7700 900457",
    notes: "Quiet tenant, always pays on time. Works in finance in the City.",
    portalStatus: "active",
    portalToken: "tnt-rc2a-7b2c",
    inviteDate: "15 Sep 2024",
    lastLogin: "25 Jun 2026",
    dateAdded: "15 Sep 2024",
  },
  {
    id: "tnt-002",
    fullName: "Emily Watson",
    email: "emily.watson@email.com",
    phone: "+44 7700 900788",
    currentPropertyId: "prop-003",
    currentPropertyName: "Oak Court",
    currentPropertyAddress: "Oak Court, 5 Oak Lane, Manchester M20 1AB",
    tenancyId: "tncy-002",
    tenancyRef: "TNCY-2025-002",
    tenancyStatus: "Active",
    emergencyContactName: "Mark Watson",
    emergencyContactPhone: "+44 7700 900789",
    notes: "PhD student at University of Manchester. Tenancy ends August 2026.",
    portalStatus: "active",
    portalToken: "tnt-oak-3d8g",
    inviteDate: "01 Sep 2025",
    lastLogin: "22 Jun 2026",
    dateAdded: "01 Sep 2025",
  },
  {
    id: "tnt-003",
    fullName: "Rachel Green",
    email: "rachel.green@email.com",
    phone: "+44 7700 900321",
    currentPropertyId: "prop-004",
    currentPropertyName: "Park View House",
    currentPropertyAddress: "17 Park View, Birmingham B15 2TT",
    tenancyId: "tncy-003",
    tenancyRef: "TNCY-2026-003",
    tenancyStatus: "Active",
    emergencyContactName: "Monica Geller",
    emergencyContactPhone: "+44 7700 900322",
    notes: "Works from home. Has requested permission for a small dog — pending landlord approval.",
    portalStatus: "active",
    portalToken: "tnt-pkv-5h1j",
    inviteDate: "10 Jan 2026",
    lastLogin: "24 Jun 2026",
    dateAdded: "10 Jan 2026",
  },
  {
    id: "tnt-004",
    fullName: "Tom Harris",
    email: "tom.harris@email.com",
    phone: "+44 7700 900555",
    currentPropertyId: "prop-002",
    currentPropertyName: "Riverside Court",
    currentPropertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    tenancyId: "tncy-004",
    tenancyRef: "TNCY-2025-004",
    tenancyStatus: "Active",
    emergencyContactName: "Lucy Harris",
    emergencyContactPhone: "+44 7700 900556",
    notes: "Joint tenancy with partner. Both work at local hospital.",
    portalStatus: "active",
    portalToken: "tnt-rsc-3e5a",
    inviteDate: "05 Aug 2025",
    lastLogin: "20 Jun 2026",
    dateAdded: "05 Aug 2025",
  },
  {
    id: "tnt-005",
    fullName: "Amir Khan",
    email: "amir.khan@email.com",
    phone: "+44 7700 900222",
    currentPropertyId: "prop-005",
    currentPropertyName: "The Willows",
    currentPropertyAddress: "22 The Willows, Edinburgh EH4 3BN",
    tenancyId: "tncy-005",
    tenancyRef: "TNCY-2026-005",
    tenancyStatus: "Active",
    emergencyContactName: "Fatima Khan",
    emergencyContactPhone: "+44 7700 900223",
    notes: "Relocated from Glasgow for work. First-time renter in Edinburgh.",
    portalStatus: "invited",
    portalToken: "tnt-wil-7k4m",
    inviteDate: "12 Jun 2026",
    lastLogin: undefined,
    dateAdded: "08 Mar 2026",
  },
  {
    id: "tnt-006",
    fullName: "Sophie Laurent",
    email: "sophie.laurent@email.com",
    phone: "+44 7700 900333",
    currentPropertyId: "prop-006",
    currentPropertyName: "12 Derby Road",
    currentPropertyAddress: "12 Derby Road, Manchester M14 5LL",
    tenancyId: "tncy-006",
    tenancyRef: "TNCY-2024-006",
    tenancyStatus: "Active",
    emergencyContactName: "Pierre Laurent",
    emergencyContactPhone: "+33 6 12 34 56 78",
    notes: "French national working at University of Manchester. Visa valid until 2027.",
    portalStatus: "active",
    portalToken: "tnt-dby-9n2p",
    inviteDate: "15 Mar 2024",
    lastLogin: "26 Jun 2026",
    dateAdded: "15 Mar 2024",
  },
  {
    id: "tnt-007",
    fullName: "Oliver Bennett",
    email: "oliver.bennett@email.com",
    phone: "+44 7700 900444",
    currentPropertyId: undefined,
    currentPropertyName: undefined,
    currentPropertyAddress: undefined,
    tenancyId: undefined,
    tenancyRef: undefined,
    tenancyStatus: undefined,
    emergencyContactName: "Charlotte Bennett",
    emergencyContactPhone: "+44 7700 900445",
    notes: "Previous tenant at Maple Gardens. Moved out March 2026. Good reference.",
    portalStatus: "disabled",
    portalToken: "tnt-mgh-1a9f",
    inviteDate: "12 Mar 2024",
    lastLogin: "10 Mar 2026",
    dateAdded: "12 Mar 2024",
  },
  {
    id: "tnt-008",
    fullName: "Daniel Craig",
    email: "daniel.craig@email.com",
    phone: "+44 7700 900888",
    currentPropertyId: undefined,
    currentPropertyName: undefined,
    currentPropertyAddress: undefined,
    tenancyId: undefined,
    tenancyRef: undefined,
    tenancyStatus: undefined,
    emergencyContactName: "",
    emergencyContactPhone: "",
    notes: "New applicant — referencing in progress. Due to move into Flat 3 Ash House.",
    portalStatus: "not_invited",
    portalToken: undefined,
    inviteDate: undefined,
    lastLogin: undefined,
    dateAdded: "20 Jun 2026",
  },
]

export const portalStatusBadge: Record<string, string> = {
  not_invited: "bg-[#94A3B8]/10 text-[#94A3B8]",
  invited: "bg-[#3B82F6]/10 text-[#3B82F6]",
  active: "bg-[#10B981]/10 text-[#10B981]",
  disabled: "bg-[#EF4444]/10 text-[#EF4444]",
}

export const portalStatusLabel: Record<string, string> = {
  not_invited: "Not Invited",
  invited: "Invited",
  active: "Active",
  disabled: "Disabled",
}