export interface Transaction {
  id: string;
  date: string;
  description: string;
  bank: string;
  bankLogo: string;
  amount: number;
  type: "income" | "expense";
  category: string;
  matched: boolean;
  matchSource?: string;
  matchStatus?: "matched" | "pending" | "unmatched" | "reconciled";
  property?: string;
  tenant?: string;
  landlord?: string;
}

export interface BankAccount {
  id: string;
  bank: string;
  bankLogo: string;
  accountName: string;
  accountNumber: string;
  sortCode: string;
  balance: number;
  currency: string;
  status: "connected" | "disconnected" | "syncing";
  lastSync: string;
  transactions: number;
}

export interface PropertyProfitability {
  id: string;
  property: string;
  address: string;
  monthlyIncome: number;
  monthlyExpenses: number;
  maintenanceCosts: number;
  netProfit: number;
  profitMargin: number;
  occupancyRate: number;
  roi: number;
}

export interface RentReconciliation {
  id: string;
  tenant: string;
  property: string;
  amount: number;
  dueDate: string;
  receivedDate: string;
  status: "paid" | "partial" | "overdue" | "pending";
  bankTransactionId: string;
  bankReference: string;
  bankName: string;
  daysLate?: number;
  amountShort?: number;
}

export interface FinancialReport {
  id: string;
  name: string;
  type: "income" | "expense" | "profit" | "reconciliation" | "landlord_summary";
  period: string;
  generatedAt: string;
  format: "csv" | "excel" | "pdf";
  size: string;
  status: "ready" | "generating";
}

export interface LandlordSummary {
  id: string;
  landlord: string;
  properties: number;
  monthlyIncome: number;
  outstandingRent: number;
  maintenanceCosts: number;
  managementFees: number;
  netIncome: number;
  yearToDate: number;
  bankAccounts: number;
  lastReconciliation: string;
}

export interface IncomeExpense {
  month: string;
  income: number;
  expenses: number;
  netProfit: number;
}

export const bankAccounts: BankAccount[] = [
  {
    id: "ba1",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    accountName: "LetHub Agency",
    accountNumber: "****4521",
    sortCode: "20-45-09",
    balance: 128450,
    currency: "GBP",
    status: "connected",
    lastSync: "2 mins ago",
    transactions: 342,
  },
  {
    id: "ba2",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    accountName: "Operations",
    accountNumber: "****7823",
    sortCode: "04-00-04",
    balance: 45680,
    currency: "GBP",
    status: "connected",
    lastSync: "15 mins ago",
    transactions: 156,
  },
  {
    id: "ba3",
    bank: "NatWest",
    bankLogo: "ri-bank-card-line",
    accountName: "Reserve",
    accountNumber: "****1102",
    sortCode: "60-16-09",
    balance: 89200,
    currency: "GBP",
    status: "connected",
    lastSync: "1 hour ago",
    transactions: 89,
  },
  {
    id: "ba4",
    bank: "HSBC",
    bankLogo: "ri-bank-card-line",
    accountName: "Client Funds",
    accountNumber: "****3391",
    sortCode: "40-09-16",
    balance: 234100,
    currency: "GBP",
    status: "syncing",
    lastSync: "In progress",
    transactions: 0,
  },
];

export const transactions: Transaction[] = [
  {
    id: "tx1",
    date: "2026-05-31",
    description: "Rent Payment - Sarah Jenkins",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: 1850,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 2A, Oak Street",
    tenant: "Sarah Jenkins",
    landlord: "James Thompson",
  },
  {
    id: "tx2",
    date: "2026-05-30",
    description: "GreenPlumb Plumbing Services",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -340,
    type: "expense",
    category: "Maintenance",
    matched: true,
    matchSource: "Contractor match",
    matchStatus: "reconciled",
    property: "12 Rose Avenue",
    tenant: "Mark Davies",
    landlord: "Susan Wright",
  },
  {
    id: "tx3",
    date: "2026-05-30",
    description: "Rent Payment - John Miller",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 2100,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 4B, Oak Street",
    tenant: "John Miller",
    landlord: "James Thompson",
  },
  {
    id: "tx4",
    date: "2026-05-29",
    description: "QuickFix Electrical",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -280,
    type: "expense",
    category: "Maintenance",
    matched: true,
    matchSource: "Job match",
    matchStatus: "reconciled",
    property: "45 Baker Street",
    tenant: "Emily Watson",
    landlord: "David Chen",
  },
  {
    id: "tx5",
    date: "2026-05-29",
    description: "Rent Payment - Emma White",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: 1650,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 1, The Crescent",
    tenant: "Emma White",
    landlord: "Michael Brown",
  },
  {
    id: "tx6",
    date: "2026-05-28",
    description: "Property Shield Insurance",
    bank: "NatWest",
    bankLogo: "ri-bank-card-line",
    amount: -650,
    type: "expense",
    category: "Insurance",
    matched: true,
    matchSource: "Policy match",
    matchStatus: "reconciled",
    property: "Multiple",
    tenant: "",
    landlord: "James Thompson",
  },
  {
    id: "tx7",
    date: "2026-05-28",
    description: "Stripe Payout",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 5200,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Stripe integration",
    matchStatus: "reconciled",
    property: "Multiple",
    tenant: "",
    landlord: "",
  },
  {
    id: "tx8",
    date: "2026-05-27",
    description: "City Council Tax",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -1200,
    type: "expense",
    category: "Council Tax",
    matched: true,
    matchSource: "Property match",
    matchStatus: "reconciled",
    property: "Multiple",
    tenant: "",
    landlord: "Susan Wright",
  },
  {
    id: "tx9",
    date: "2026-05-27",
    description: "Rent Payment - Robert Lee",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: 2300,
    type: "income",
    category: "Rent",
    matched: false,
    matchStatus: "pending",
    property: "",
    tenant: "Robert Lee",
    landlord: "",
  },
  {
    id: "tx10",
    date: "2026-05-26",
    description: "BuildRight Construction Ltd",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -4500,
    type: "expense",
    category: "Maintenance",
    matched: true,
    matchSource: "Job match",
    matchStatus: "reconciled",
    property: "8 The Crescent",
    tenant: "",
    landlord: "Michael Brown",
  },
  {
    id: "tx11",
    date: "2026-05-26",
    description: "Rent Payment - Lisa Green",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 1400,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 3, Park View",
    tenant: "Lisa Green",
    landlord: "David Chen",
  },
  {
    id: "tx12",
    date: "2026-05-25",
    description: "British Gas",
    bank: "NatWest",
    bankLogo: "ri-bank-card-line",
    amount: -180,
    type: "expense",
    category: "Utilities",
    matched: true,
    matchSource: "Property match",
    matchStatus: "reconciled",
    property: "12 Rose Avenue",
    tenant: "",
    landlord: "Susan Wright",
  },
  {
    id: "tx13",
    date: "2026-05-25",
    description: "GoCardless Payout",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 3800,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "GoCardless integration",
    matchStatus: "reconciled",
    property: "Multiple",
    tenant: "",
    landlord: "",
  },
  {
    id: "tx14",
    date: "2026-05-24",
    description: "Rent Payment - Tom Harris",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: 1950,
    type: "income",
    category: "Rent",
    matched: false,
    matchStatus: "unmatched",
    property: "",
    tenant: "",
    landlord: "",
  },
  {
    id: "tx15",
    date: "2026-05-24",
    description: "WindowCare Ltd",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -220,
    type: "expense",
    category: "Maintenance",
    matched: true,
    matchSource: "Job match",
    matchStatus: "reconciled",
    property: "Flat 7 Park View",
    tenant: "",
    landlord: "James Thompson",
  },
  {
    id: "tx16",
    date: "2026-05-23",
    description: "Rent Payment - Amanda Scott",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 1750,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 5, Oak Street",
    tenant: "Amanda Scott",
    landlord: "Susan Wright",
  },
  {
    id: "tx17",
    date: "2026-05-23",
    description: "PropertyWise Ltd",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -520,
    type: "expense",
    category: "Management",
    matched: true,
    matchSource: "Agency match",
    matchStatus: "reconciled",
    property: "Multiple",
    tenant: "",
    landlord: "",
  },
  {
    id: "tx18",
    date: "2026-05-22",
    description: "Rent Payment - David Lee",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: 2200,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 2, Baker Street",
    tenant: "David Lee",
    landlord: "Michael Brown",
  },
  {
    id: "tx19",
    date: "2026-05-22",
    description: "Emergency Plumber 24",
    bank: "Barclays",
    bankLogo: "ri-bank-card-line",
    amount: -180,
    type: "expense",
    category: "Maintenance",
    matched: true,
    matchSource: "Job match",
    matchStatus: "reconciled",
    property: "45 Baker Street",
    tenant: "",
    landlord: "David Chen",
  },
  {
    id: "tx20",
    date: "2026-05-21",
    description: "Rent Payment - Rachel Adams",
    bank: "Monzo",
    bankLogo: "ri-bank-card-line",
    amount: 1600,
    type: "income",
    category: "Rent",
    matched: true,
    matchSource: "Auto-matched",
    matchStatus: "reconciled",
    property: "Flat 6, The Crescent",
    tenant: "Rachel Adams",
    landlord: "James Thompson",
  },
];

export const propertyProfitability: PropertyProfitability[] = [
  {
    id: "p1",
    property: "Flat 2A, Oak Street",
    address: "2A Oak Street, London NW1",
    monthlyIncome: 1850,
    monthlyExpenses: 420,
    maintenanceCosts: 150,
    netProfit: 1430,
    profitMargin: 77,
    occupancyRate: 100,
    roi: 6.2,
  },
  {
    id: "p2",
    property: "Flat 4B, Oak Street",
    address: "4B Oak Street, London NW1",
    monthlyIncome: 2100,
    monthlyExpenses: 480,
    maintenanceCosts: 200,
    netProfit: 1620,
    profitMargin: 77,
    occupancyRate: 100,
    roi: 7.1,
  },
  {
    id: "p3",
    property: "12 Rose Avenue",
    address: "12 Rose Avenue, Manchester M3",
    monthlyIncome: 1650,
    monthlyExpenses: 350,
    maintenanceCosts: 180,
    netProfit: 1300,
    profitMargin: 79,
    occupancyRate: 100,
    roi: 5.8,
  },
  {
    id: "p4",
    property: "45 Baker Street",
    address: "45 Baker Street, Bristol BS1",
    monthlyIncome: 1950,
    monthlyExpenses: 440,
    maintenanceCosts: 280,
    netProfit: 1510,
    profitMargin: 77,
    occupancyRate: 100,
    roi: 6.5,
  },
  {
    id: "p5",
    property: "Flat 1, The Crescent",
    address: "1 The Crescent, Birmingham B2",
    monthlyIncome: 1650,
    monthlyExpenses: 390,
    maintenanceCosts: 100,
    netProfit: 1260,
    profitMargin: 76,
    occupancyRate: 100,
    roi: 5.5,
  },
  {
    id: "p6",
    property: "8 The Crescent",
    address: "8 The Crescent, Birmingham B2",
    monthlyIncome: 2300,
    monthlyExpenses: 520,
    maintenanceCosts: 350,
    netProfit: 1780,
    profitMargin: 77,
    occupancyRate: 100,
    roi: 7.8,
  },
  {
    id: "p7",
    property: "Flat 3, Park View",
    address: "3 Park View, Leeds LS1",
    monthlyIncome: 1400,
    monthlyExpenses: 310,
    maintenanceCosts: 120,
    netProfit: 1090,
    profitMargin: 78,
    occupancyRate: 100,
    roi: 4.9,
  },
  {
    id: "p8",
    property: "Flat 7 Park View",
    address: "7 Park View, Leeds LS1",
    monthlyIncome: 1750,
    monthlyExpenses: 380,
    maintenanceCosts: 160,
    netProfit: 1370,
    profitMargin: 78,
    occupancyRate: 100,
    roi: 6.0,
  },
];

export const rentReconciliations: RentReconciliation[] = [
  {
    id: "rr1",
    tenant: "Sarah Jenkins",
    property: "Flat 2A, Oak Street",
    amount: 1850,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-31",
    status: "paid",
    bankTransactionId: "tx1",
    bankReference: "BARC-2026-0531-4521",
    bankName: "Barclays",
  },
  {
    id: "rr2",
    tenant: "John Miller",
    property: "Flat 4B, Oak Street",
    amount: 2100,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-30",
    status: "paid",
    bankTransactionId: "tx3",
    bankReference: "MONZ-2026-0530-7823",
    bankName: "Monzo",
  },
  {
    id: "rr3",
    tenant: "Emma White",
    property: "Flat 1, The Crescent",
    amount: 1650,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-29",
    status: "paid",
    bankTransactionId: "tx5",
    bankReference: "BARC-2026-0529-4521",
    bankName: "Barclays",
  },
  {
    id: "rr4",
    tenant: "Robert Lee",
    property: "Flat 5, Park View",
    amount: 2300,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-27",
    status: "partial",
    bankTransactionId: "tx9",
    bankReference: "BARC-2026-0527-4521",
    bankName: "Barclays",
    amountShort: 300,
    daysLate: 2,
  },
  {
    id: "rr5",
    tenant: "Lisa Green",
    property: "Flat 3, Park View",
    amount: 1400,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-26",
    status: "paid",
    bankTransactionId: "tx11",
    bankReference: "MONZ-2026-0526-7823",
    bankName: "Monzo",
  },
  {
    id: "rr6",
    tenant: "Tom Harris",
    property: "Flat 3, Oak Street",
    amount: 1950,
    dueDate: "2026-05-31",
    receivedDate: "",
    status: "overdue",
    bankTransactionId: "tx14",
    bankReference: "BARC-2026-0524-4521",
    bankName: "Barclays",
    daysLate: 7,
  },
  {
    id: "rr7",
    tenant: "Amanda Scott",
    property: "Flat 5, Oak Street",
    amount: 1750,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-23",
    status: "paid",
    bankTransactionId: "tx16",
    bankReference: "MONZ-2026-0523-7823",
    bankName: "Monzo",
  },
  {
    id: "rr8",
    tenant: "David Lee",
    property: "Flat 2, Baker Street",
    amount: 2200,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-22",
    status: "paid",
    bankTransactionId: "tx18",
    bankReference: "BARC-2026-0522-4521",
    bankName: "Barclays",
  },
  {
    id: "rr9",
    tenant: "Rachel Adams",
    property: "Flat 6, The Crescent",
    amount: 1600,
    dueDate: "2026-05-31",
    receivedDate: "2026-05-21",
    status: "paid",
    bankTransactionId: "tx20",
    bankReference: "MONZ-2026-0521-7823",
    bankName: "Monzo",
  },
  {
    id: "rr10",
    tenant: "Mark Davies",
    property: "12 Rose Avenue",
    amount: 1650,
    dueDate: "2026-05-31",
    receivedDate: "",
    status: "overdue",
    bankTransactionId: "",
    bankReference: "",
    bankName: "",
    daysLate: 7,
  },
];

export const financialReports: FinancialReport[] = [
  {
    id: "fr1",
    name: "Monthly Income Report - May 2026",
    type: "income",
    period: "May 2026",
    generatedAt: "2026-05-31",
    format: "csv",
    size: "24 KB",
    status: "ready",
  },
  {
    id: "fr2",
    name: "Expense Breakdown - May 2026",
    type: "expense",
    period: "May 2026",
    generatedAt: "2026-05-31",
    format: "excel",
    size: "45 KB",
    status: "ready",
  },
  {
    id: "fr3",
    name: "Property Profitability - Q2 2026",
    type: "profit",
    period: "Q2 2026",
    generatedAt: "2026-05-31",
    format: "pdf",
    size: "128 KB",
    status: "ready",
  },
  {
    id: "fr4",
    name: "Rent Reconciliation - May 2026",
    type: "reconciliation",
    period: "May 2026",
    generatedAt: "2026-05-31",
    format: "excel",
    size: "32 KB",
    status: "ready",
  },
  {
    id: "fr5",
    name: "Landlord Financial Summary - May 2026",
    type: "landlord_summary",
    period: "May 2026",
    generatedAt: "2026-05-31",
    format: "pdf",
    size: "215 KB",
    status: "ready",
  },
  {
    id: "fr6",
    name: "Year to Date Financial Report",
    type: "profit",
    period: "Jan - May 2026",
    generatedAt: "2026-05-31",
    format: "pdf",
    size: "512 KB",
    status: "ready",
  },
];

export const landlordSummaries: LandlordSummary[] = [
  {
    id: "ls1",
    landlord: "James Thompson",
    properties: 4,
    monthlyIncome: 7500,
    outstandingRent: 0,
    maintenanceCosts: 450,
    managementFees: 750,
    netIncome: 6300,
    yearToDate: 31500,
    bankAccounts: 2,
    lastReconciliation: "2026-05-31",
  },
  {
    id: "ls2",
    landlord: "Susan Wright",
    properties: 3,
    monthlyIncome: 5050,
    outstandingRent: 1650,
    maintenanceCosts: 380,
    managementFees: 505,
    netIncome: 4165,
    yearToDate: 20825,
    bankAccounts: 1,
    lastReconciliation: "2026-05-31",
  },
  {
    id: "ls3",
    landlord: "David Chen",
    properties: 3,
    monthlyIncome: 5100,
    outstandingRent: 0,
    maintenanceCosts: 320,
    managementFees: 510,
    netIncome: 4270,
    yearToDate: 21350,
    bankAccounts: 1,
    lastReconciliation: "2026-05-31",
  },
  {
    id: "ls4",
    landlord: "Michael Brown",
    properties: 2,
    monthlyIncome: 3950,
    outstandingRent: 0,
    maintenanceCosts: 180,
    managementFees: 395,
    netIncome: 3375,
    yearToDate: 16875,
    bankAccounts: 2,
    lastReconciliation: "2026-05-30",
  },
  {
    id: "ls5",
    landlord: "Emma Wilson",
    properties: 2,
    monthlyIncome: 3200,
    outstandingRent: 0,
    maintenanceCosts: 220,
    managementFees: 320,
    netIncome: 2660,
    yearToDate: 13300,
    bankAccounts: 1,
    lastReconciliation: "2026-05-31",
  },
  {
    id: "ls6",
    landlord: "Robert Clark",
    properties: 1,
    monthlyIncome: 2400,
    outstandingRent: 0,
    maintenanceCosts: 150,
    managementFees: 240,
    netIncome: 2010,
    yearToDate: 10050,
    bankAccounts: 1,
    lastReconciliation: "2026-05-31",
  },
];

export const incomeExpenseData: IncomeExpense[] = [
  { month: "Jan", income: 18500, expenses: 4200, netProfit: 14300 },
  { month: "Feb", income: 19200, expenses: 3900, netProfit: 15300 },
  { month: "Mar", income: 18800, expenses: 4500, netProfit: 14300 },
  { month: "Apr", income: 19500, expenses: 4100, netProfit: 15400 },
  { month: "May", income: 20100, expenses: 4600, netProfit: 15500 },
];

export const categoryBreakdown = [
  { category: "Rent", income: 16800, expense: 0, color: "#C28A78" },
  { category: "Maintenance", income: 0, expense: 1850, color: "#EF4444" },
  { category: "Insurance", income: 0, expense: 650, color: "#F59E0B" },
  { category: "Council Tax", income: 0, expense: 1200, color: "#3B82F6" },
  { category: "Utilities", income: 0, expense: 480, color: "#14B8A6" },
  { category: "Management", income: 0, expense: 520, color: "#8B5CF6" },
  { category: "Stripe Fees", income: -120, expense: 0, color: "#6366F1" },
  { category: "GoCardless", income: 0, expense: 0, color: "#10B981" },
];