export interface ImportRecord {
  id: string;
  fileName: string;
  source: string;
  format: "csv" | "excel" | "json" | "api";
  totalRecords: number;
  imported: number;
  skipped: number;
  errors: number;
  duplicates: number;
  status: "pending" | "processing" | "completed" | "failed" | "cancelled";
  uploadedAt: string;
  completedAt?: string;
  uploadedBy: string;
  failedRows?: ImportFailedRow[];
}

export interface ImportFailedRow {
  row: number;
  address: string;
  reason: string;
}

export interface FieldMapping {
  sourceField: string;
  targetField: string;
  confidence: number;
  autoMapped: boolean;
  required: boolean;
}

export interface PreviewProperty {
  id: string;
  address: string;
  city: string;
  postcode: string;
  propertyType: string;
  bedrooms: number;
  bathrooms: number;
  landlord: string;
  landlordEmail: string;
  landlordPhone: string;
  tenant: string;
  tenantEmail: string;
  tenantPhone: string;
  rent: number;
  deposit: number;
  epcRating: string;
  gasExpiry: string;
  eicrExpiry: string;
  tenancyStartDate: string;
  tenancyEndDate: string;
  status: string;
  validationErrors: string[];
  validationWarnings: string[];
  isDuplicate: boolean;
  duplicateOf?: string;
}

export interface PMSIntegration {
  id: string;
  name: string;
  icon: string;
  description: string;
  connected: boolean;
  lastSync?: string;
  properties: number;
  syncStatus?: "idle" | "syncing" | "error";
}

export interface ValidationRule {
  id: string;
  name: string;
  description: string;
  severity: "error" | "warning";
  appliesTo: string;
  active: boolean;
}

export const importHistory: ImportRecord[] = [
  {
    id: "imp-001",
    fileName: "properties_may_2026.csv",
    source: "CSV Upload",
    format: "csv",
    totalRecords: 45,
    imported: 42,
    skipped: 1,
    errors: 2,
    duplicates: 3,
    status: "completed",
    uploadedAt: "2026-05-28 14:23",
    completedAt: "2026-05-28 14:25",
    uploadedBy: "Sarah Davies",
    failedRows: [
      { row: 23, address: "17 High Street, London", reason: "Missing landlord email" },
      { row: 38, address: "9 Church Road, Watford", reason: "Invalid postcode format" },
    ],
  },
  {
    id: "imp-002",
    fileName: "portfolio_import.xlsx",
    source: "Excel Upload",
    format: "excel",
    totalRecords: 128,
    imported: 124,
    skipped: 0,
    errors: 4,
    duplicates: 8,
    status: "completed",
    uploadedAt: "2026-05-25 09:15",
    completedAt: "2026-05-25 09:22",
    uploadedBy: "Mark Thompson",
    failedRows: [
      { row: 17, address: "44 Park Lane, Bristol", reason: "Rent amount missing" },
      { row: 56, address: "2 Main Street, Cardiff", reason: "EPC rating invalid" },
      { row: 89, address: "33 Green Road, Leeds", reason: "Duplicate address detected" },
      { row: 112, address: "78 Queen Street, Edinburgh", reason: "Tenancy end date before start date" },
    ],
  },
  {
    id: "imp-003",
    fileName: "legacy_properties.csv",
    source: "Legacy PMS Export",
    format: "csv",
    totalRecords: 67,
    imported: 0,
    skipped: 0,
    errors: 67,
    duplicates: 0,
    status: "failed",
    uploadedAt: "2026-05-22 16:45",
    uploadedBy: "James O'Connor",
  },
  {
    id: "imp-004",
    fileName: "new_landlord_batch.xlsx",
    source: "Excel Upload",
    format: "excel",
    totalRecords: 18,
    imported: 18,
    skipped: 0,
    errors: 0,
    duplicates: 0,
    status: "completed",
    uploadedAt: "2026-05-20 11:30",
    completedAt: "2026-05-20 11:31",
    uploadedBy: "Sarah Davies",
  },
  {
    id: "imp-005",
    fileName: "api_sync",
    source: "Property Management System",
    format: "api",
    totalRecords: 256,
    imported: 248,
    skipped: 0,
    errors: 8,
    duplicates: 12,
    status: "completed",
    uploadedAt: "2026-05-18 02:00",
    completedAt: "2026-05-18 02:05",
    uploadedBy: "System",
  },
  {
    id: "imp-006",
    fileName: "quick_import.csv",
    source: "CSV Upload",
    format: "csv",
    totalRecords: 12,
    imported: 0,
    skipped: 0,
    errors: 0,
    duplicates: 0,
    status: "processing",
    uploadedAt: "2026-05-31 10:15",
    uploadedBy: "Sarah Davies",
  },
];

export const fieldMappings: FieldMapping[] = [
  { sourceField: "address", targetField: "Property Address", confidence: 98, autoMapped: true, required: true },
  { sourceField: "city", targetField: "City", confidence: 96, autoMapped: true, required: true },
  { sourceField: "postcode", targetField: "Postcode", confidence: 99, autoMapped: true, required: true },
  { sourceField: "type", targetField: "Property Type", confidence: 92, autoMapped: true, required: false },
  { sourceField: "bedrooms", targetField: "Bedrooms", confidence: 95, autoMapped: true, required: false },
  { sourceField: "bathrooms", targetField: "Bathrooms", confidence: 95, autoMapped: true, required: false },
  { sourceField: "landlord_name", targetField: "Landlord Name", confidence: 88, autoMapped: true, required: true },
  { sourceField: "landlord_email", targetField: "Landlord Email", confidence: 85, autoMapped: true, required: false },
  { sourceField: "landlord_phone", targetField: "Landlord Phone", confidence: 82, autoMapped: true, required: false },
  { sourceField: "tenant_name", targetField: "Tenant Name", confidence: 87, autoMapped: true, required: false },
  { sourceField: "tenant_email", targetField: "Tenant Email", confidence: 84, autoMapped: true, required: false },
  { sourceField: "monthly_rent", targetField: "Monthly Rent", confidence: 97, autoMapped: true, required: false },
  { sourceField: "deposit", targetField: "Deposit Amount", confidence: 94, autoMapped: true, required: false },
  { sourceField: "epc", targetField: "EPC Rating", confidence: 91, autoMapped: true, required: false },
  { sourceField: "gas_cert", targetField: "Gas Safety Cert", confidence: 90, autoMapped: true, required: false },
  { sourceField: "eicr", targetField: "EICR Date", confidence: 89, autoMapped: true, required: false },
  { sourceField: "gas_expiry", targetField: "Gas Safety Expiry", confidence: 88, autoMapped: true, required: false },
  { sourceField: "eicr_expiry", targetField: "EICR Expiry", confidence: 88, autoMapped: true, required: false },
  { sourceField: "tenancy_start", targetField: "Tenancy Start Date", confidence: 86, autoMapped: true, required: false },
  { sourceField: "tenancy_end", targetField: "Tenancy End Date", confidence: 86, autoMapped: true, required: false },
  { sourceField: "status", targetField: "Property Status", confidence: 93, autoMapped: true, required: false },
  { sourceField: "notes", targetField: "Notes", confidence: 75, autoMapped: false, required: false },
  { sourceField: "photos", targetField: "Photos", confidence: 70, autoMapped: false, required: false },
  { sourceField: "furnished", targetField: "Furnished", confidence: 88, autoMapped: true, required: false },
];

export const previewProperties: PreviewProperty[] = [
  {
    id: "p1",
    address: "14 Rosebery Avenue",
    city: "London",
    postcode: "N10 2XX",
    propertyType: "Flat",
    bedrooms: 2,
    bathrooms: 1,
    landlord: "James Thompson",
    landlordEmail: "j.thompson@email.com",
    landlordPhone: "07700 900123",
    tenant: "Sarah Jenkins",
    tenantEmail: "s.jenkins@email.com",
    tenantPhone: "07700 900456",
    rent: 1850,
    deposit: 2775,
    epcRating: "C",
    gasExpiry: "2027-03-12",
    eicrExpiry: "2026-06-19",
    tenancyStartDate: "2024-09-15",
    tenancyEndDate: "2026-09-14",
    status: "Occupied",
    validationErrors: [],
    validationWarnings: [],
    isDuplicate: false,
  },
  {
    id: "p2",
    address: "22 Baker Street",
    city: "London",
    postcode: "NW1 6XE",
    propertyType: "House",
    bedrooms: 3,
    bathrooms: 2,
    landlord: "Susan Wright",
    landlordEmail: "s.wright@email.com",
    landlordPhone: "07700 900789",
    tenant: "John Miller",
    tenantEmail: "j.miller@email.com",
    tenantPhone: "07700 900012",
    rent: 2100,
    deposit: 3150,
    epcRating: "B",
    gasExpiry: "2026-11-20",
    eicrExpiry: "2027-04-15",
    tenancyStartDate: "2024-08-05",
    tenancyEndDate: "2026-08-04",
    status: "Occupied",
    validationErrors: [],
    validationWarnings: [],
    isDuplicate: false,
  },
  {
    id: "p3",
    address: "8 Park Crescent",
    city: "Manchester",
    postcode: "M3 4JA",
    propertyType: "Flat",
    bedrooms: 1,
    bathrooms: 1,
    landlord: "David Chen",
    landlordEmail: "d.chen@email.com",
    landlordPhone: "07700 900345",
    tenant: "",
    tenantEmail: "",
    tenantPhone: "",
    rent: 1200,
    deposit: 1800,
    epcRating: "D",
    gasExpiry: "2027-01-08",
    eicrExpiry: "2025-11-30",
    tenancyStartDate: "",
    tenancyEndDate: "",
    status: "Available",
    validationErrors: [],
    validationWarnings: ["No tenant assigned", "EICR has expired"],
    isDuplicate: false,
  },
  {
    id: "p4",
    address: "45 Oak Lane",
    city: "Bristol",
    postcode: "BS1 3AA",
    propertyType: "Terraced",
    bedrooms: 2,
    bathrooms: 1,
    landlord: "Michael Brown",
    landlordEmail: "m.brown@email.com",
    landlordPhone: "07700 900678",
    tenant: "Emma White",
    tenantEmail: "e.white@email.com",
    tenantPhone: "07700 900901",
    rent: 1650,
    deposit: 2475,
    epcRating: "C",
    gasExpiry: "2026-08-14",
    eicrExpiry: "2028-02-28",
    tenancyStartDate: "2025-03-01",
    tenancyEndDate: "2027-02-28",
    status: "Occupied",
    validationErrors: [],
    validationWarnings: [],
    isDuplicate: false,
  },
  {
    id: "p5",
    address: "12 Rose Avenue",
    city: "Manchester",
    postcode: "M3 4JA",
    propertyType: "Flat",
    bedrooms: 2,
    bathrooms: 1,
    landlord: "Susan Wright",
    landlordEmail: "s.wright@email.com",
    landlordPhone: "07700 900789",
    tenant: "Mark Davies",
    tenantEmail: "m.davies@email.com",
    tenantPhone: "07700 900234",
    rent: 1650,
    deposit: 2475,
    epcRating: "C",
    gasExpiry: "2026-05-30",
    eicrExpiry: "2027-09-10",
    tenancyStartDate: "2025-01-15",
    tenancyEndDate: "2026-01-14",
    status: "Occupied",
    validationErrors: ["Duplicate address: 12 Rose Avenue already exists"],
    validationWarnings: [],
    isDuplicate: true,
    duplicateOf: "PROP-0034",
  },
  {
    id: "p6",
    address: "",
    city: "London",
    postcode: "SW1A 1AA",
    propertyType: "Flat",
    bedrooms: 1,
    bathrooms: 1,
    landlord: "",
    landlordEmail: "",
    landlordPhone: "",
    tenant: "",
    tenantEmail: "",
    tenantPhone: "",
    rent: 0,
    deposit: 0,
    epcRating: "",
    gasExpiry: "",
    eicrExpiry: "",
    tenancyStartDate: "",
    tenancyEndDate: "",
    status: "Unknown",
    validationErrors: ["Address is required", "Landlord is required", "Rent amount is invalid"],
    validationWarnings: ["EPC rating missing", "No tenant information"],
    isDuplicate: false,
  },
  {
    id: "p7",
    address: "99 High Street",
    city: "Leeds",
    postcode: "LS1 4BR",
    propertyType: "Semi-Detached",
    bedrooms: 3,
    bathrooms: 2,
    landlord: "Emma Wilson",
    landlordEmail: "e.wilson@email.com",
    landlordPhone: "07700 900567",
    tenant: "Tom Harris",
    tenantEmail: "t.harris@email.com",
    tenantPhone: "07700 900890",
    rent: 1950,
    deposit: 2925,
    epcRating: "B",
    gasExpiry: "2027-06-01",
    eicrExpiry: "2028-01-15",
    tenancyStartDate: "2025-06-01",
    tenancyEndDate: "2027-05-31",
    status: "Occupied",
    validationErrors: [],
    validationWarnings: [],
    isDuplicate: false,
  },
  {
    id: "p8",
    address: "3 The Crescent",
    city: "Birmingham",
    postcode: "B2 4QA",
    propertyType: "Flat",
    bedrooms: 2,
    bathrooms: 1,
    landlord: "Robert Clark",
    landlordEmail: "r.clark@email.com",
    landlordPhone: "07700 900432",
    tenant: "Lisa Green",
    tenantEmail: "l.green@email.com",
    tenantPhone: "07700 900765",
    rent: 1400,
    deposit: 2100,
    epcRating: "D",
    gasExpiry: "2026-12-01",
    eicrExpiry: "2027-07-20",
    tenancyStartDate: "2024-11-01",
    tenancyEndDate: "2026-10-31",
    status: "Occupied",
    validationErrors: [],
    validationWarnings: ["EPC rating is D — consider energy improvements"],
    isDuplicate: false,
  },
  {
    id: "p9",
    address: "67 Victoria Road",
    city: "Edinburgh",
    postcode: "EH4 3JN",
    propertyType: "House",
    bedrooms: 4,
    bathrooms: 2,
    landlord: "James Thompson",
    landlordEmail: "j.thompson@email.com",
    landlordPhone: "07700 900123",
    tenant: "",
    tenantEmail: "",
    tenantPhone: "",
    rent: 2800,
    deposit: 4200,
    epcRating: "C",
    gasExpiry: "2026-09-15",
    eicrExpiry: "2027-03-01",
    tenancyStartDate: "",
    tenancyEndDate: "",
    status: "Available",
    validationErrors: [],
    validationWarnings: ["No tenant assigned", "Postcode format differs from standard"],
    isDuplicate: false,
  },
  {
    id: "p10",
    address: "12 Rose Avenue",
    city: "Manchester",
    postcode: "M3 4JA",
    propertyType: "Flat",
    bedrooms: 2,
    bathrooms: 1,
    landlord: "Susan Wright",
    landlordEmail: "s.wright@email.com",
    landlordPhone: "07700 900789",
    tenant: "Mark Davies",
    tenantEmail: "m.davies@email.com",
    tenantPhone: "07700 900234",
    rent: 1650,
    deposit: 2475,
    epcRating: "C",
    gasExpiry: "2026-05-30",
    eicrExpiry: "2027-09-10",
    tenancyStartDate: "2025-01-15",
    tenancyEndDate: "2026-01-14",
    status: "Occupied",
    validationErrors: ["Duplicate address: 12 Rose Avenue already exists (2 occurrences)"],
    validationWarnings: [],
    isDuplicate: true,
    duplicateOf: "PROP-0034",
  },
];

export const pmsIntegrations: PMSIntegration[] = [
  {
    id: "pms1",
    name: "Goodlord",
    icon: "ri-building-4-line",
    description: "Import properties, tenancies, and documents from Goodlord",
    connected: true,
    lastSync: "2026-05-31 02:00",
    properties: 89,
    syncStatus: "idle",
  },
  {
    id: "pms2",
    name: "Arthur Online",
    icon: "ri-global-line",
    description: "Sync properties, tenants, and compliance data from Arthur Online",
    connected: true,
    lastSync: "2026-05-30 18:00",
    properties: 156,
    syncStatus: "idle",
  },
  {
    id: "pms3",
    name: "Reapit",
    icon: "ri-database-line",
    description: "Import full property portfolios from Reapit CRM",
    connected: false,
    properties: 0,
  },
  {
    id: "pms4",
    name: "Dezrez",
    icon: "ri-hard-drive-line",
    description: "Import properties and contacts from Dezrez",
    connected: false,
    properties: 0,
  },
  {
    id: "pms5",
    name: "Street",
    icon: "ri-map-pin-line",
    description: "Sync properties and tenancies from Street",
    connected: true,
    lastSync: "2026-05-29 12:00",
    properties: 45,
    syncStatus: "idle",
  },
  {
    id: "pms6",
    name: "Rightmove API",
    icon: "ri-upload-cloud-line",
    description: "Import property listings from Rightmove",
    connected: false,
    properties: 0,
  },
];

export const validationRules: ValidationRule[] = [
  {
    id: "vr1",
    name: "Required Address",
    description: "Property address must be present and not empty",
    severity: "error",
    appliesTo: "address",
    active: true,
  },
  {
    id: "vr2",
    name: "Valid UK Postcode",
    description: "Postcode must match standard UK format",
    severity: "error",
    appliesTo: "postcode",
    active: true,
  },
  {
    id: "vr3",
    name: "Required Landlord",
    description: "Each property must have a landlord assigned",
    severity: "error",
    appliesTo: "landlord",
    active: true,
  },
  {
    id: "vr4",
    name: "Valid Rent Amount",
    description: "Monthly rent must be a positive number greater than 0",
    severity: "error",
    appliesTo: "rent",
    active: true,
  },
  {
    id: "vr5",
    name: "Duplicate Address",
    description: "Detect if a property with the same address already exists",
    severity: "error",
    appliesTo: "address",
    active: true,
  },
  {
    id: "vr6",
    name: "EPC Rating",
    description: "EPC rating should be present for compliance tracking",
    severity: "warning",
    appliesTo: "epc",
    active: true,
  },
  {
    id: "vr7",
    name: "Valid Email",
    description: "Landlord and tenant emails should be valid format",
    severity: "warning",
    appliesTo: "email",
    active: true,
  },
  {
    id: "vr8",
    name: "Deposit Amount",
    description: "Deposit should not exceed 5 weeks rent",
    severity: "warning",
    appliesTo: "deposit",
    active: true,
  },
  {
    id: "vr9",
    name: "Furnished Status",
    description: "Furnished status should be specified",
    severity: "warning",
    appliesTo: "furnished",
    active: false,
  },
  {
    id: "vr10",
    name: "Photo Count",
    description: "At least 3 photos should be uploaded per property",
    severity: "warning",
    appliesTo: "photos",
    active: false,
  },
  {
    id: "vr11",
    name: "Gas Safety Expiry",
    description: "Gas safety certificate must be within valid date range",
    severity: "error",
    appliesTo: "gas_expiry",
    active: true,
  },
  {
    id: "vr12",
    name: "EICR Expiry",
    description: "EICR must be within 5-year validity window",
    severity: "warning",
    appliesTo: "eicr_expiry",
    active: true,
  },
  {
    id: "vr13",
    name: "Tenancy Dates",
    description: "Tenancy end date must be after start date",
    severity: "error",
    appliesTo: "tenancy_dates",
    active: true,
  },
];

export const availableFields = [
  "Property Address",
  "City",
  "Postcode",
  "Property Type",
  "Bedrooms",
  "Bathrooms",
  "Landlord Name",
  "Landlord Email",
  "Landlord Phone",
  "Tenant Name",
  "Tenant Email",
  "Tenant Phone",
  "Monthly Rent",
  "Deposit Amount",
  "EPC Rating",
  "Gas Safety Cert",
  "EICR Date",
  "Gas Safety Expiry",
  "EICR Expiry",
  "Tenancy Start Date",
  "Tenancy End Date",
  "Property Status",
  "Furnished",
  "Pets Allowed",
  "Smoking Allowed",
  "Notes",
  "Photos",
  "Keys Held",
  "Alarm Code",
  "Insurance Policy",
  "Date Acquired",
  "Purchase Price",
  "Current Value",
];

export const sourceFields = [
  "address",
  "address_line_1",
  "address_line_2",
  "city",
  "town",
  "postcode",
  "zip",
  "type",
  "property_type",
  "category",
  "bedrooms",
  "beds",
  "no_bedrooms",
  "bathrooms",
  "baths",
  "no_bathrooms",
  "landlord_name",
  "landlord",
  "owner",
  "landlord_email",
  "landlord_email_address",
  "landlord_phone",
  "landlord_telephone",
  "landlord_mobile",
  "tenant_name",
  "tenant",
  "occupant",
  "tenant_email",
  "tenant_email_address",
  "tenant_phone",
  "tenant_telephone",
  "monthly_rent",
  "rent",
  "rental_amount",
  "weekly_rent",
  "deposit",
  "security_deposit",
  "bond",
  "epc",
  "epc_rating",
  "energy_rating",
  "gas_cert",
  "gas_safety",
  "cp12",
  "eicr",
  "electrical_cert",
  "gas_expiry",
  "gas_cert_expiry",
  "gas_safety_expiry",
  "eicr_expiry",
  "eicr_cert_expiry",
  "electrical_expiry",
  "tenancy_start",
  "tenancy_start_date",
  "lease_start",
  "start_date",
  "tenancy_end",
  "tenancy_end_date",
  "lease_end",
  "end_date",
  "status",
  "property_status",
  "availability",
  "furnished",
  "furnished_status",
  "pets",
  "pets_allowed",
  "smoking",
  "smoking_allowed",
  "notes",
  "comments",
  "description",
  "photos",
  "images",
  "pictures",
];