export interface RentSchedule {
  id: string
  propertyName: string
  propertyId: string
  tenantName: string
  tenantId: string
  ownerName: string
  ownerId: string
  tenancyRef: string
  tenancyId: string
  rentAmount: number
  frequency: "monthly" | "weekly" | "fortnightly"
  dueDay: number
  nextDueDate: string
  tenancyStatus: string
  scheduleStatus: "active" | "paused" | "ended"
  depositAmount: number
  depositScheme: string
  paymentMethod: string
  lastPaidDate: string | null
  lastPaidAmount: number | null
}

export const rentSchedules: RentSchedule[] = [
  {
    id: "rs-001",
    propertyName: "12 Rose Avenue",
    propertyId: "1",
    tenantName: "John Miller",
    tenantId: "tnt-001",
    ownerName: "James Richardson",
    ownerId: "own-001",
    tenancyRef: "TNCY-2024-001",
    tenancyId: "tncy-001",
    rentAmount: 1850,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 1850,
    depositScheme: "MyDeposits",
    paymentMethod: "Bank Transfer",
    lastPaidDate: "01 Jun 2026",
    lastPaidAmount: 1850,
  },
  {
    id: "rs-002",
    propertyName: "Flat 4B Oak Street",
    propertyId: "2",
    tenantName: "Sarah Jenkins",
    tenantId: "tnt-002",
    ownerName: "David Thompson",
    ownerId: "own-002",
    tenancyRef: "TNCY-2025-002",
    tenancyId: "tncy-002",
    rentAmount: 950,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 950,
    depositScheme: "TDS",
    paymentMethod: "Direct Debit",
    lastPaidDate: "03 Jun 2026",
    lastPaidAmount: 950,
  },
  {
    id: "rs-003",
    propertyName: "45 Baker Street",
    propertyId: "3",
    tenantName: "Emily Carter",
    tenantId: "tnt-003",
    ownerName: "Sarah Walker",
    ownerId: "own-003",
    tenancyRef: "TNCY-2025-003",
    tenancyId: "tncy-003",
    rentAmount: 2100,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 2100,
    depositScheme: "DPS",
    paymentMethod: "Standing Order",
    lastPaidDate: "01 May 2026",
    lastPaidAmount: 2100,
  },
  {
    id: "rs-004",
    propertyName: "8 The Crescent",
    propertyId: "4",
    tenantName: "Michael Brown",
    tenantId: "tnt-004",
    ownerName: "Margaret Hughes",
    ownerId: "own-004",
    tenancyRef: "TNCY-2024-004",
    tenancyId: "tncy-004",
    rentAmount: 1650,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 1650,
    depositScheme: "MyDeposits",
    paymentMethod: "Standing Order",
    lastPaidDate: "05 May 2026",
    lastPaidAmount: 1650,
  },
  {
    id: "rs-005",
    propertyName: "34 Maple Gardens",
    propertyId: "5",
    tenantName: "David Thompson",
    tenantId: "tnt-005",
    ownerName: "Sarah Walker",
    ownerId: "own-003",
    tenancyRef: "TNCY-2024-005",
    tenancyId: "tncy-005",
    rentAmount: 2400,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 2400,
    depositScheme: "TDS",
    paymentMethod: "Standing Order",
    lastPaidDate: "01 Jun 2026",
    lastPaidAmount: 2400,
  },
  {
    id: "rs-006",
    propertyName: "Flat 7 Park View",
    propertyId: "6",
    tenantName: "Lisa Chen",
    tenantId: "tnt-006",
    ownerName: "David Thompson",
    ownerId: "own-002",
    tenancyRef: "TNCY-2025-006",
    tenancyId: "tncy-006",
    rentAmount: 1200,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 1200,
    depositScheme: "DPS",
    paymentMethod: "Bank Transfer",
    lastPaidDate: "10 Apr 2026",
    lastPaidAmount: 1200,
  },
  {
    id: "rs-007",
    propertyName: "21 High Street",
    propertyId: "7",
    tenantName: "Robert Green",
    tenantId: "tnt-007",
    ownerName: "Robert Stewart",
    ownerId: "own-005",
    tenancyRef: "TNCY-2025-007",
    tenancyId: "tncy-007",
    rentAmount: 800,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 800,
    depositScheme: "MyDeposits",
    paymentMethod: "Direct Debit",
    lastPaidDate: "01 May 2026",
    lastPaidAmount: 800,
  },
  {
    id: "rs-008",
    propertyName: "Unit 3 Riverside Court",
    propertyId: "8",
    tenantName: "Emma Wilson",
    tenantId: "tnt-008",
    ownerName: "James Richardson",
    ownerId: "own-001",
    tenancyRef: "TNCY-2024-008",
    tenancyId: "tncy-008",
    rentAmount: 1400,
    frequency: "monthly",
    dueDay: 1,
    nextDueDate: "01 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 1400,
    depositScheme: "TDS",
    paymentMethod: "Bank Transfer",
    lastPaidDate: "01 Jun 2026",
    lastPaidAmount: 1400,
  },
  {
    id: "rs-009",
    propertyName: "55 Elm Grove",
    propertyId: "9",
    tenantName: "Tom Harris",
    tenantId: "tnt-009",
    ownerName: "Emma Wilson",
    ownerId: "own-006",
    tenancyRef: "TNCY-2026-009",
    tenancyId: "tncy-009",
    rentAmount: 1100,
    frequency: "monthly",
    dueDay: 5,
    nextDueDate: "05 Jul 2026",
    tenancyStatus: "Active",
    scheduleStatus: "active",
    depositAmount: 1100,
    depositScheme: "DPS",
    paymentMethod: "Standing Order",
    lastPaidDate: "05 Jun 2026",
    lastPaidAmount: 1100,
  },
  {
    id: "rs-010",
    propertyName: "Flat 2C Willow Court",
    propertyId: "10",
    tenantName: "Anna Kowalski",
    tenantId: "tnt-010",
    ownerName: "Priya Patel",
    ownerId: "own-007",
    tenancyRef: "TNCY-2025-010",
    tenancyId: "tncy-010",
    rentAmount: 750,
    frequency: "weekly",
    dueDay: 1,
    nextDueDate: "30 Jun 2026",
    tenancyStatus: "Ending",
    scheduleStatus: "active",
    depositAmount: 750,
    depositScheme: "MyDeposits",
    paymentMethod: "Bank Transfer",
    lastPaidDate: "23 Jun 2026",
    lastPaidAmount: 750,
  },
]

export const scheduleStatusBadge: Record<string, string> = {
  active: "bg-[#10B981]/10 text-[#10B981]",
  paused: "bg-[#F59E0B]/10 text-[#F59E0B]",
  ended: "bg-[#94A3B8]/10 text-[#94A3B8]",
}

export const scheduleStatusLabel: Record<string, string> = {
  active: "Active",
  paused: "Paused",
  ended: "Ended",
}

export const frequencyLabel: Record<string, string> = {
  monthly: "Monthly",
  weekly: "Weekly",
  fortnightly: "Fortnightly",
}