export interface ComplianceItem {
  id: string;
  type: string;
  category: string;
  propertyId: string;
  propertyName: string;
  propertyAddress: string;
  status: string;
  expiryDate: string;
  daysLeft: number;
  issuedDate: string;
  issuer: string;
  referenceNumber: string;
  documentUrl: string;
  notes: string;
  icon: string;
  color: string;
  requiredByLaw: boolean;
  renewalPeriod: string;
  lastAction: string;
  lastActionDate: string;
}

export interface ComplianceAlert {
  id: string;
  type: string;
  title: string;
  message: string;
  property: string;
  severity: string;
  date: string;
  read: boolean;
  complianceId: string;
}

export interface PropertyCompliance {
  propertyId: string;
  propertyName: string;
  address: string;
  city: string;
  postcode: string;
  type: string;
  isHMO: boolean;
  complianceItems: string[];
  overallStatus: string;
  compliantCount: number;
  expiringSoonCount: number;
  expiredCount: number;
  totalCount: number;
  lastAuditDate: string;
  image: string;
}

export const complianceItems: ComplianceItem[] = [
  {
    id: "comp1",
    type: "Gas Safety Certificate",
    category: "Gas",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "12 Mar 2027",
    daysLeft: 285,
    issuedDate: "13 Mar 2026",
    issuer: "SafeGas Engineers Ltd",
    referenceNumber: "GSC-2026-04589",
    documentUrl: "#",
    notes: "Annual gas safety check completed. All appliances passed inspection.",
    icon: "ri-fire-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Issued",
    lastActionDate: "13 Mar 2026",
  },
  {
    id: "comp2",
    type: "EICR Report",
    category: "Electrical",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Expiring Soon",
    expiryDate: "18 Jun 2026",
    daysLeft: 18,
    issuedDate: "19 Jun 2021",
    issuer: "London Electrical Services",
    referenceNumber: "EICR-LON-2021-8923",
    documentUrl: "#",
    notes: "C2 observation on bathroom lighting circuit. Requires remedial work within 28 days.",
    icon: "ri-flashlight-line",
    color: "bg-[#F59E0B]",
    requiredByLaw: true,
    renewalPeriod: "Every 5 years",
    lastAction: "Reminder sent",
    lastActionDate: "28 May 2026",
  },
  {
    id: "comp3",
    type: "EPC Certificate",
    category: "Energy",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Expired",
    expiryDate: "02 Jan 2026",
    daysLeft: -150,
    issuedDate: "03 Jan 2016",
    issuer: "EPC Direct Wales",
    referenceNumber: "EPC-8942-5673-9012",
    documentUrl: "#",
    notes: "Rating: D. Expired over 5 months ago. Required for new tenancies.",
    icon: "ri-leaf-line",
    color: "bg-[#10B981]",
    requiredByLaw: true,
    renewalPeriod: "10 years",
    lastAction: "Expired",
    lastActionDate: "02 Jan 2026",
  },
  {
    id: "comp4",
    type: "Legionella Assessment",
    category: "Water",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Expiring Soon",
    expiryDate: "15 Jun 2026",
    daysLeft: 15,
    issuedDate: "16 Jun 2025",
    issuer: "WaterSafe Compliance",
    referenceNumber: "LEG-BRI-2025-3471",
    documentUrl: "#",
    notes: "Low risk assessment. No action needed. Due for renewal within 2 weeks.",
    icon: "ri-drop-line",
    color: "bg-[#3B82F6]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Reminder sent",
    lastActionDate: "30 May 2026",
  },
  {
    id: "comp5",
    type: "Smoke Alarm Check",
    category: "Fire",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "01 Jul 2026",
    daysLeft: 31,
    issuedDate: "01 Jul 2025",
    issuer: "FireSafe London",
    referenceNumber: "SMK-LON-2025-1204",
    documentUrl: "#",
    notes: "All mains-wired smoke alarms tested and functioning. Battery backups confirmed.",
    icon: "ri-alarm-warning-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Tested",
    lastActionDate: "01 Jul 2025",
  },
  {
    id: "comp6",
    type: "Carbon Monoxide Check",
    category: "Gas",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "12 Mar 2027",
    daysLeft: 285,
    issuedDate: "13 Mar 2026",
    issuer: "SafeGas Engineers Ltd",
    referenceNumber: "CO-LON-2026-04589",
    documentUrl: "#",
    notes: "CO alarm tested and functioning correctly. Positioned near boiler room.",
    icon: "ri-sensor-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Tested",
    lastActionDate: "13 Mar 2026",
  },
  {
    id: "comp7",
    type: "HMO Compliance",
    category: "Licensing",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "30 Sep 2027",
    daysLeft: 487,
    issuedDate: "01 Oct 2024",
    issuer: "London Borough of Tower Hamlets",
    referenceNumber: "HMO-LON-2024-7892",
    documentUrl: "#",
    notes: "Mandatory HMO licence valid. 3 occupants. Minimum room sizes met.",
    icon: "ri-building-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: true,
    renewalPeriod: "5 years",
    lastAction: "Renewed",
    lastActionDate: "01 Oct 2024",
  },
  {
    id: "comp8",
    type: "Building Insurance",
    category: "Insurance",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Valid",
    expiryDate: "01 Jan 2027",
    daysLeft: 215,
    issuedDate: "02 Jan 2026",
    issuer: "AXA Landlord Insurance",
    referenceNumber: "AXA-2026-LL-44521",
    documentUrl: "#",
    notes: "Buildings and contents cover. £500 excess. Includes public liability.",
    icon: "ri-shield-check-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: false,
    renewalPeriod: "Annually",
    lastAction: "Renewed",
    lastActionDate: "02 Jan 2026",
  },
  {
    id: "comp9",
    type: "Gas Safety Certificate",
    category: "Gas",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Valid",
    expiryDate: "20 Nov 2026",
    daysLeft: 175,
    issuedDate: "21 Nov 2025",
    issuer: "Bristol Gas Solutions",
    referenceNumber: "GSC-BRI-2025-2201",
    documentUrl: "#",
    notes: "All gas appliances safe. Cooker hob regulator replaced.",
    icon: "ri-fire-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Issued",
    lastActionDate: "21 Nov 2025",
  },
  {
    id: "comp10",
    type: "EPC Certificate",
    category: "Energy",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "15 Aug 2028",
    daysLeft: 807,
    issuedDate: "16 Aug 2018",
    issuer: "EPC Direct London",
    referenceNumber: "EPC-1029-3847-5612",
    documentUrl: "#",
    notes: "Rating: C. Valid until 2028.",
    icon: "ri-leaf-line",
    color: "bg-[#10B981]",
    requiredByLaw: true,
    renewalPeriod: "10 years",
    lastAction: "Issued",
    lastActionDate: "16 Aug 2018",
  },
  {
    id: "comp11",
    type: "EICR Report",
    category: "Electrical",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Expired",
    expiryDate: "10 Apr 2026",
    daysLeft: -51,
    issuedDate: "11 Apr 2021",
    issuer: "Bristol Electrical Ltd",
    referenceNumber: "EICR-BRI-2021-4402",
    documentUrl: "#",
    notes: "Expired nearly 2 months ago. New EICR required immediately.",
    icon: "ri-flashlight-line",
    color: "bg-[#F59E0B]",
    requiredByLaw: true,
    renewalPeriod: "Every 5 years",
    lastAction: "Expired",
    lastActionDate: "10 Apr 2026",
  },
  {
    id: "comp12",
    type: "Smoke Alarm Check",
    category: "Fire",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Action Required",
    expiryDate: "05 May 2026",
    daysLeft: -26,
    issuedDate: "05 May 2025",
    issuer: "FireSafe Bristol",
    referenceNumber: "SMK-BRI-2025-0822",
    documentUrl: "#",
    notes: "OVERDUE. Smoke alarm check not completed. Tenant has been notified.",
    icon: "ri-alarm-warning-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Reminder sent",
    lastActionDate: "25 May 2026",
  },
  {
    id: "comp13",
    type: "Legionella Assessment",
    category: "Water",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Valid",
    expiryDate: "22 Oct 2026",
    daysLeft: 144,
    issuedDate: "23 Oct 2025",
    issuer: "Cardiff Water Safety",
    referenceNumber: "LEG-CDF-2025-6701",
    documentUrl: "#",
    notes: "Low risk. No issues found. Hot water tank at 60C.",
    icon: "ri-drop-line",
    color: "bg-[#3B82F6]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Issued",
    lastActionDate: "23 Oct 2025",
  },
  {
    id: "comp14",
    type: "Carbon Monoxide Check",
    category: "Gas",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Valid",
    expiryDate: "20 Nov 2026",
    daysLeft: 175,
    issuedDate: "21 Nov 2025",
    issuer: "Bristol Gas Solutions",
    referenceNumber: "CO-BRI-2025-2201",
    documentUrl: "#",
    notes: "CO alarm tested. Battery backup OK.",
    icon: "ri-sensor-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Tested",
    lastActionDate: "21 Nov 2025",
  },
  {
    id: "comp15",
    type: "HMO Compliance",
    category: "Licensing",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "N/A",
    expiryDate: "—",
    daysLeft: 999,
    issuedDate: "—",
    issuer: "—",
    referenceNumber: "—",
    documentUrl: "#",
    notes: "Not applicable. Property has 2 occupants.",
    icon: "ri-building-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: false,
    renewalPeriod: "N/A",
    lastAction: "—",
    lastActionDate: "—",
  },
  {
    id: "comp16",
    type: "Building Insurance",
    category: "Insurance",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "01 Jul 2026",
    daysLeft: 31,
    issuedDate: "02 Jul 2025",
    issuer: "Direct Line Landlord",
    referenceNumber: "DL-2025-LL-78234",
    documentUrl: "#",
    notes: "Buildings insurance. Rent protection included. Auto-renewal enabled.",
    icon: "ri-shield-check-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: false,
    renewalPeriod: "Annually",
    lastAction: "Renewed",
    lastActionDate: "02 Jul 2025",
  },
  {
    id: "comp17",
    type: "Gas Safety Certificate",
    category: "Gas",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Expired",
    expiryDate: "25 Dec 2025",
    daysLeft: -158,
    issuedDate: "26 Dec 2024",
    issuer: "Cardiff Gas Safe",
    referenceNumber: "GSC-CDF-2024-9902",
    documentUrl: "#",
    notes: "Expired over 5 months. URGENT. Gas safety check required immediately.",
    icon: "ri-fire-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Expired",
    lastActionDate: "25 Dec 2025",
  },
  {
    id: "comp18",
    type: "EPC Certificate",
    category: "Energy",
    propertyId: "p2",
    propertyName: "Riverside Court",
    propertyAddress: "Unit 3, Riverside Court, Bristol BS1 4ST",
    status: "Valid",
    expiryDate: "30 Nov 2028",
    daysLeft: 913,
    issuedDate: "01 Dec 2018",
    issuer: "EPC Direct Bristol",
    referenceNumber: "EPC-4456-7823-1190",
    documentUrl: "#",
    notes: "Rating: B. Valid until 2028.",
    icon: "ri-leaf-line",
    color: "bg-[#10B981]",
    requiredByLaw: true,
    renewalPeriod: "10 years",
    lastAction: "Issued",
    lastActionDate: "01 Dec 2018",
  },
  {
    id: "comp19",
    type: "EICR Report",
    category: "Electrical",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Valid",
    expiryDate: "14 Feb 2028",
    daysLeft: 624,
    issuedDate: "15 Feb 2023",
    issuer: "Wales Electrical Services",
    referenceNumber: "EICR-CDF-2023-1128",
    documentUrl: "#",
    notes: "Satisfactory. No observations. Next inspection 2028.",
    icon: "ri-flashlight-line",
    color: "bg-[#F59E0B]",
    requiredByLaw: true,
    renewalPeriod: "Every 5 years",
    lastAction: "Issued",
    lastActionDate: "15 Feb 2023",
  },
  {
    id: "comp20",
    type: "Smoke Alarm Check",
    category: "Fire",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Valid",
    expiryDate: "08 Apr 2027",
    daysLeft: 312,
    issuedDate: "09 Apr 2026",
    issuer: "FireSafe Cardiff",
    referenceNumber: "SMK-CDF-2026-0145",
    documentUrl: "#",
    notes: "All alarms tested. 3 mains-wired, 2 battery. All functioning.",
    icon: "ri-alarm-warning-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Tested",
    lastActionDate: "09 Apr 2026",
  },
  {
    id: "comp21",
    type: "Carbon Monoxide Check",
    category: "Gas",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Expired",
    expiryDate: "25 Dec 2025",
    daysLeft: -158,
    issuedDate: "26 Dec 2024",
    issuer: "Cardiff Gas Safe",
    referenceNumber: "CO-CDF-2024-9902",
    documentUrl: "#",
    notes: "Expired with gas safety. URGENT. CO alarm check required.",
    icon: "ri-sensor-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Expired",
    lastActionDate: "25 Dec 2025",
  },
  {
    id: "comp22",
    type: "Building Insurance",
    category: "Insurance",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Valid",
    expiryDate: "28 Feb 2027",
    daysLeft: 273,
    issuedDate: "01 Mar 2026",
    issuer: "Aviva Landlord",
    referenceNumber: "AVI-2026-LL-33456",
    documentUrl: "#",
    notes: "Buildings, contents, and rent guarantee. £250 excess.",
    icon: "ri-shield-check-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: false,
    renewalPeriod: "Annually",
    lastAction: "Renewed",
    lastActionDate: "01 Mar 2026",
  },
  {
    id: "comp23",
    type: "HMO Compliance",
    category: "Licensing",
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    propertyAddress: "34 Maple Gardens, Cardiff CF10 3BZ",
    status: "Valid",
    expiryDate: "31 Dec 2027",
    daysLeft: 579,
    issuedDate: "01 Jan 2024",
    issuer: "Cardiff City Council",
    referenceNumber: "HMO-CDF-2024-3409",
    documentUrl: "#",
    notes: "Additional licence. 4 sharers. All conditions met.",
    icon: "ri-building-line",
    color: "bg-[#8B5CF6]",
    requiredByLaw: true,
    renewalPeriod: "3 years",
    lastAction: "Renewed",
    lastActionDate: "01 Jan 2024",
  },
  {
    id: "comp24",
    type: "Fire Risk Assessment",
    category: "Fire",
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    propertyAddress: "12 Rose Avenue, London E1 6AN",
    status: "Valid",
    expiryDate: "30 Sep 2026",
    daysLeft: 122,
    issuedDate: "01 Oct 2025",
    issuer: "London Fire Safety Ltd",
    referenceNumber: "FRA-LON-2025-4452",
    documentUrl: "#",
    notes: "Satisfactory. Escape routes clear. Fire doors maintained.",
    icon: "ri-fire-line",
    color: "bg-[#EF4444]",
    requiredByLaw: true,
    renewalPeriod: "Annually",
    lastAction: "Issued",
    lastActionDate: "01 Oct 2025",
  },
];

export const complianceAlerts: ComplianceAlert[] = [
  {
    id: "alert1",
    type: "expired",
    title: "Gas Safety Certificate Expired",
    message: "Maple Gardens House gas safety expired 158 days ago. Immediate action required.",
    property: "Maple Gardens House",
    severity: "critical",
    date: "25 Dec 2025",
    read: false,
    complianceId: "comp17",
  },
  {
    id: "alert2",
    type: "expired",
    title: "EPC Certificate Expired",
    message: "Maple Gardens House EPC expired 150 days ago. Required for new tenancies.",
    property: "Maple Gardens House",
    severity: "critical",
    date: "02 Jan 2026",
    read: false,
    complianceId: "comp3",
  },
  {
    id: "alert3",
    type: "expired",
    title: "EICR Report Expired",
    message: "Riverside Court EICR expired 51 days ago. New electrical inspection needed.",
    property: "Riverside Court",
    severity: "critical",
    date: "10 Apr 2026",
    read: false,
    complianceId: "comp11",
  },
  {
    id: "alert4",
    type: "action",
    title: "Smoke Alarm Check Overdue",
    message: "Riverside Court smoke alarm check is 26 days overdue. Tenant notified.",
    property: "Riverside Court",
    severity: "warning",
    date: "05 May 2026",
    read: false,
    complianceId: "comp12",
  },
  {
    id: "alert5",
    type: "expiring",
    title: "EICR Expiring Soon",
    message: "Rose Court Flat 2A EICR expires in 18 days. Schedule renewal now.",
    property: "Rose Court Flat 2A",
    severity: "warning",
    date: "18 Jun 2026",
    read: false,
    complianceId: "comp2",
  },
  {
    id: "alert6",
    type: "expiring",
    title: "Legionella Assessment Expiring",
    message: "Riverside Court legionella assessment expires in 15 days.",
    property: "Riverside Court",
    severity: "warning",
    date: "15 Jun 2026",
    read: false,
    complianceId: "comp4",
  },
  {
    id: "alert7",
    type: "expiring",
    title: "Smoke Alarm Check Expiring",
    message: "Rose Court Flat 2A smoke alarm check expires in 31 days.",
    property: "Rose Court Flat 2A",
    severity: "warning",
    date: "01 Jul 2026",
    read: false,
    complianceId: "comp5",
  },
  {
    id: "alert8",
    type: "expiring",
    title: "Building Insurance Expiring",
    message: "Rose Court Flat 2A insurance expires in 31 days. Auto-renewal is enabled.",
    property: "Rose Court Flat 2A",
    severity: "info",
    date: "01 Jul 2026",
    read: false,
    complianceId: "comp16",
  },
  {
    id: "alert9",
    type: "expired",
    title: "Carbon Monoxide Check Expired",
    message: "Maple Gardens House CO check expired with gas safety. Urgent renewal needed.",
    property: "Maple Gardens House",
    severity: "critical",
    date: "25 Dec 2025",
    read: false,
    complianceId: "comp21",
  },
  {
    id: "alert10",
    type: "action",
    title: "C2 Observation on EICR",
    message: "Rose Court Flat 2A EICR has C2 observation. Remedial work required within 28 days.",
    property: "Rose Court Flat 2A",
    severity: "warning",
    date: "18 Jun 2026",
    read: false,
    complianceId: "comp2",
  },
];

export const propertyCompliance: PropertyCompliance[] = [
  {
    propertyId: "p1",
    propertyName: "Rose Court Flat 2A",
    address: "12 Rose Avenue",
    city: "London",
    postcode: "E1 6AN",
    type: "Flat",
    isHMO: true,
    complianceItems: ["comp1", "comp2", "comp5", "comp6", "comp7", "comp10", "comp16", "comp24"],
    overallStatus: "Attention",
    compliantCount: 6,
    expiringSoonCount: 2,
    expiredCount: 0,
    totalCount: 8,
    lastAuditDate: "13 Mar 2026",
    image: "https://readdy.ai/api/search-image?query=Modern London apartment building exterior with contemporary brick and glass facade, large windows, clean residential street, professional architectural photography, soft overcast daylight, UK property, clean simple background with muted tones and warm neutral colours",
  },
  {
    propertyId: "p2",
    propertyName: "Riverside Court",
    address: "Unit 3, Riverside Court",
    city: "Bristol",
    postcode: "BS1 4ST",
    type: "Flat",
    isHMO: false,
    complianceItems: ["comp4", "comp8", "comp9", "comp11", "comp12", "comp14", "comp15", "comp18"],
    overallStatus: "Critical",
    compliantCount: 4,
    expiringSoonCount: 1,
    expiredCount: 2,
    totalCount: 8,
    lastAuditDate: "21 Nov 2025",
    image: "https://readdy.ai/api/search-image?query=Contemporary riverside apartment building in Bristol UK, modern waterfront residential complex with balconies, glass and steel architecture, professional architectural photography, clean simple background with muted tones and warm neutral colours",
  },
  {
    propertyId: "p3",
    propertyName: "Maple Gardens House",
    address: "34 Maple Gardens",
    city: "Cardiff",
    postcode: "CF10 3BZ",
    type: "Semi-Detached",
    isHMO: true,
    complianceItems: ["comp3", "comp13", "comp17", "comp19", "comp20", "comp21", "comp22", "comp23"],
    overallStatus: "Critical",
    compliantCount: 4,
    expiringSoonCount: 0,
    expiredCount: 3,
    totalCount: 8,
    lastAuditDate: "09 Apr 2026",
    image: "https://readdy.ai/api/search-image?query=Modern British semi-detached house exterior with brick and render facade, well-maintained front garden with driveway, suburban UK residential area, professional real estate photography, clean simple background with muted tones and warm neutral colours",
  },
];

export const complianceCategories = [
  { label: "All", value: "All" },
  { label: "Gas", value: "Gas" },
  { label: "Electrical", value: "Electrical" },
  { label: "Energy", value: "Energy" },
  { label: "Water", value: "Water" },
  { label: "Fire", value: "Fire" },
  { label: "Licensing", value: "Licensing" },
  { label: "Insurance", value: "Insurance" },
];